"""One-command reproduction of PolyForge's committed measurement records.

Re-derives the generated analysis records (RESULTS.md, ADVANCED.md, and —
when the raw databases are present — RESULTS_V2/V3.md, FAIRNESS_V2.md) and
every figure into a scratch directory, then diffs them against the committed
versions. The committed records are frozen by the pre-registration ground
rules and are never written to.

Tiers, detected automatically per input:

  git      a clean `git clone`: run-level statistics and figures rebuild
           from the committed `eval/results/metrics_*.csv.gz` exports and
           the committed security JSON/CSVs. Timeseries figures (fig09) and
           the v2/v3/VTC records need the raw DuckDBs and are skipped with
           a notice.
  archive  with the Zenodo-archived DuckDB files restored into
           `eval/results/`: everything above plus timeseries figures and
           the v2/v3/fairness records.

Float note: the csv.gz exports round-trip DuckDB float32 columns (the
latency percentiles) at float32 precision (~1e-11 absolute here) — seven
orders of magnitude below the 4-significant-figure reporting precision, so
re-derived tables match the committed records.

Usage (from the repo root):
    python scripts/reproduce.py --check   # inputs + deps + plan, no run
    python scripts/reproduce.py           # rebuild into reproduce_out/ and diff
    python scripts/reproduce.py --out DIR # custom scratch directory
"""

from __future__ import annotations

import argparse
import difflib
import os
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
ANALYSIS = REPO_ROOT / "research" / "analysis"
RESULTS = REPO_ROOT / "eval" / "results"
FIGURES = RESULTS / "figures"

# What run_analysis.py can produce, and the raw database each record needs
# beyond the committed exports (None = fully rebuildable from git). All five
# are None: every campaign here now has either a run-level csv.gz export or,
# where the analysis needs the timeseries, a committed aggregate of exactly
# the query it runs (eval/scripts/export_timeseries_agg.py).
RECORDS = [
    ("RESULTS.md", None),
    ("ADVANCED.md", None),
    ("RESULTS_V2.md", None),
    ("FAIRNESS_V2.md", None),
    ("RESULTS_V3.md", None),
]

# Campaign records produced by a standalone script rather than by
# run_analysis.py: (script, argv, record). Each reads its campaign's committed
# csv.gz export when the DuckDB is absent, so this whole block rebuilds on a
# clean clone. fig18/fig19 ride along with their campaigns' scripts.
CAMPAIGN_RECORDS = [
    ("analysis_concurrency.py", [], "RESULTS_CONCURRENCY.md"),
    ("analysis_learned.py", [], "RESULTS_LEARNED.md"),
    ("analysis_risk.py", [], "RESULTS_RISK.md"),
    ("analysis_risk_budget.py", [], "RESULTS_RISK_BUDGET.md"),
    ("analysis_tenant_scale.py", [], "RESULTS_TENANT_SCALE.md"),
    ("analysis_chaos.py", [], "RESULTS_CHAOS_SIM.md"),
    ("analysis_econ.py", ["tier"], "RESULTS_TIER_RATIO.md"),
    ("analysis_econ.py", ["hk"], "RESULTS_HK_ADOPTION.md"),
    ("analysis_econ.py", ["lm"], "RESULTS_LM_ADOPTION.md"),
    ("analysis_econ.py", ["mixp95"], "RESULTS_MIXTURE_P95.md"),
    ("analysis_econ.py", ["tierwu"], "RESULTS_TIER_WU.md"),
    ("analysis_eviction_parity.py", [], "RESULTS_EVICTION_PARITY.md"),
    # Live-derived records were entirely outside this gate until session 35 —
    # the audit's D10 finding. phase7_ordinal now falls back to its committed
    # csv exports, so it rebuilds on a clean clone like every other record.
    ("analysis_order_permutation.py", [], "RESULTS_ORDER_PERMUTATION.md"),
    ("phase7_ordinal.py", [], "PHASE7_ORDINAL.md"),
    # The M3 cost separation was outside this gate entirely until session 37 —
    # guarantee.py was imported by its own test and nothing else, so the
    # paper's only formal contribution could not be regenerated by any
    # committed command. It needs no campaign data: it derives from the
    # plant constants, so it rebuilds on a clean clone unconditionally.
    ("analysis_separation.py", [], "RESULTS_SEPARATION.md"),
    ("analysis_trace_parity.py", [], "RESULTS_TRACE_PARITY.md"),
    # Both traces of the budget-parity campaign are in, so the record joins
    # the gate as PREREG_BUDGET_PARITY requires. It was deliberately held out
    # while only Azure had landed: an interim record cannot carry a
    # byte-identity guarantee it is about to break.
    ("analysis_budget_parity.py", [], "RESULTS_BUDGET_PARITY.md"),
    # WP3: the -joint-control ablation re-scored against a tier rule that is
    # not absorbing. Reads its own campaign DB, falling back to the committed
    # export, so a clean clone rebuilds it like every other record.
    ("analysis_layered_fix.py", [], "RESULTS_LAYERED_FIX.md"),
]

CORE_EXPORTS = ["metrics_full.csv.gz", "metrics_ablations.csv.gz",
                "metrics_forecasters.csv.gz", "metrics_realism.csv.gz"]
DEPS = ["duckdb", "pandas", "scipy", "statsmodels", "matplotlib"]


def check_inputs() -> tuple[list[str], list[str]]:
    """Returns (problems, notices). Problems block the git tier."""
    problems, notices = [], []
    for name in CORE_EXPORTS:
        if not (RESULTS / name).exists():
            problems.append(f"missing committed export: eval/results/{name}")
    for mod in DEPS:
        try:
            __import__(mod)
        except ImportError:
            problems.append(f"missing python package: {mod} "
                            "(pip install -r eval/requirements.txt)")
    for record, db in RECORDS:
        if db and not (RESULTS / db).exists():
            notices.append(f"{record}: needs eval/results/{db} "
                           "(Zenodo archive) — will be skipped")
    if not (RESULTS / "raw_sim.duckdb").exists():
        notices.append("fig09_adaptation_trace: needs raw_sim.duckdb "
                       "(timeseries live only in the archive) — will be skipped")
    return problems, notices


def diff_record(name: str, out_dir: Path) -> str:
    committed, rebuilt = ANALYSIS / name, out_dir / name
    if not rebuilt.exists():
        return "skipped (needs archive)" if not_available(name) else "NOT PRODUCED"
    if not committed.exists():
        return "no committed version to compare"
    a = committed.read_text(encoding="utf-8").splitlines()
    b = rebuilt.read_text(encoding="utf-8").splitlines()
    delta = [ln for ln in difflib.unified_diff(a, b, lineterm="")
             if ln[:1] in "+-" and ln[:3] not in ("+++", "---")]
    if not delta:
        return "MATCH (byte-identical)"
    (out_dir / f"diff_{name}.txt").write_text(
        "\n".join(difflib.unified_diff(a, b, f"committed/{name}",
                                       f"rebuilt/{name}", lineterm="")),
        encoding="utf-8")
    return f"drift: {len(delta)} changed lines (see diff_{name}.txt)"


def not_available(record: str) -> bool:
    db = dict(RECORDS).get(record)
    return bool(db) and not (RESULTS / db).exists()


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true",
                    help="verify inputs and dependencies, print the plan, exit")
    ap.add_argument("--out", type=Path, default=REPO_ROOT / "reproduce_out",
                    help="scratch output directory (default: reproduce_out/)")
    args = ap.parse_args()

    problems, notices = check_inputs()
    tier = "archive" if (RESULTS / "raw_sim.duckdb").exists() else "git"
    print(f"tier: {tier}")
    for n in notices:
        print(f"  note: {n}")
    for p in problems:
        print(f"  PROBLEM: {p}")
    if args.check:
        print("check", "FAILED" if problems else "OK")
        return 1 if problems else 0
    if problems:
        return 1

    out_dir = args.out.resolve()
    fig_dir = out_dir / "figures"
    fig_dir.mkdir(parents=True, exist_ok=True)
    # Clear this script's own artifacts from a previous run before rebuilding.
    # Without it, anything that fails to rebuild now is still counted from the
    # last run's leftovers — which overstates exactly the claim this script
    # exists to substantiate. (Only known artifact patterns are removed, never
    # the directory itself: --out can point anywhere.)
    stale = 0
    for pattern in ("fig*.pdf", "fig*.png", "FIGURES.md"):
        for path in fig_dir.glob(pattern):
            path.unlink()
            stale += 1
    for pattern in ("*.md", "diff_*.txt"):
        for path in out_dir.glob(pattern):
            path.unlink()
            stale += 1
    if stale:
        print(f"cleared {stale} artifact(s) from the previous run")
    env = {**os.environ,
           "POLYFORGE_ANALYSIS_OUT": str(out_dir),
           "POLYFORGE_FIG_DIR": str(fig_dir)}
    print(f"rebuilding into {out_dir} ...")
    proc = subprocess.run([sys.executable, "run_analysis.py"],
                          cwd=ANALYSIS, env=env)
    if proc.returncode != 0:
        print("run_analysis.py FAILED")
        return proc.returncode

    # Campaign scripts, each in its own process so one failure cannot take the
    # rest of the report with it.
    failed_campaigns = []
    for script, argv, record in CAMPAIGN_RECORDS:
        proc = subprocess.run([sys.executable, script, *argv], cwd=ANALYSIS,
                              env=env, capture_output=True, text=True)
        if proc.returncode != 0:
            failed_campaigns.append((record, proc.stderr.strip().splitlines()[-1:]))

    print("\n=== reproduction report ===")
    all_records = [r for r, _ in RECORDS] + [r for _, _, r in CAMPAIGN_RECORDS]
    width = max(len(r) for r in all_records)
    matched = 0
    for record, _ in RECORDS:
        status = diff_record(record, out_dir)
        matched += status.startswith("MATCH")
        print(f"  {record:<{width}} {status}")
    for _, _, record in CAMPAIGN_RECORDS:
        status = diff_record(record, out_dir)
        matched += status.startswith("MATCH")
        print(f"  {record:<{width}} {status}")
    print(f"  {'records':<{width}} {matched}/{len(all_records)} byte-identical")
    for record, err in failed_campaigns:
        print(f"    campaign script for {record} exited nonzero: "
              f"{' '.join(err) or 'see output above'}")

    rebuilt_figs = sorted(p.stem for p in fig_dir.glob("fig*.pdf"))
    committed_figs = sorted(p.stem for p in FIGURES.glob("fig*.pdf"))
    missing = [f for f in committed_figs if f not in rebuilt_figs]
    print(f"  {'figures':<{width}} {len(rebuilt_figs)}/{len(committed_figs)} "
          f"rebuilt as vector PDF + 600-DPI PNG")
    for f in missing:
        if tier == "git" or f == "fig09_adaptation_trace":
            print(f"    not rebuilt: {f} (needs archive timeseries)")
        else:
            print(f"    not rebuilt: {f}")
    print("committed records and figures were not modified.")

    # Exit status must carry the verdict. This previously returned 0
    # unconditionally, so a CI job or a reviewer running `python
    # scripts/reproduce.py` saw green while every record drifted and every
    # campaign script crashed — the gate reported failure only in prose.
    drifted = len(all_records) - matched
    if drifted or failed_campaigns:
        print(f"\nFAILED: {drifted} record(s) not byte-identical, "
              f"{len(failed_campaigns)} campaign script(s) exited nonzero.")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
