"""One-command reproduction of PolyForge's committed measurement records.

Re-derives the generated analysis records (RESULTS.md, ADVANCED.md, and —
when the raw databases are present — RESULTS_V2/V3.md, FAIRNESS_V2.md) and
every figure into a scratch directory, then diffs them against the committed
versions. The committed records are frozen by the pre-registration ground
rules and are never written to.

Tiers, detected automatically per input:

  git      a clean `git clone`: run-level statistics and figures rebuild
           from the committed `eval/results/metrics_*.csv.gz` exports and
           the committed security JSON/CSVs. Timeseries figures (fig09) and
           the v2/v3/VTC records need the raw DuckDBs and are skipped with
           a notice.
  archive  with the Zenodo-archived DuckDB files restored into
           `eval/results/`: everything above plus timeseries figures and
           the v2/v3/fairness records.

Float note: the csv.gz exports round-trip DuckDB float32 columns (the
latency percentiles) at float32 precision (~1e-11 absolute here) — seven
orders of magnitude below the 4-significant-figure reporting precision, so
re-derived tables match the committed records.

Usage (from the repo root):
    python scripts/reproduce.py --check   # inputs + deps + plan, no run
    python scripts/reproduce.py           # rebuild into reproduce_out/ and diff
    python scripts/reproduce.py --out DIR # custom scratch directory
"""

from __future__ import annotations

import argparse
import difflib
import json
import os
import re
import subprocess
import sys
from importlib.metadata import version
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
ANALYSIS = REPO_ROOT / "research" / "analysis"
CRLF, LF = bytes([13, 10]), bytes([10])
RESULTS = REPO_ROOT / "eval" / "results"
FIGURES = RESULTS / "figures"

# What run_analysis.py can produce, and the raw database each record needs
# beyond the committed exports (None = fully rebuildable from git). All five
# are None: every campaign here now has either a run-level csv.gz export or,
# where the analysis needs the timeseries, a committed aggregate of exactly
# the query it runs (eval/scripts/export_timeseries_agg.py).
RECORDS = [
    ("RESULTS.md", None),
    ("ADVANCED.md", None),
    ("RESULTS_V2.md", None),
    ("FAIRNESS_V2.md", None),
    ("RESULTS_V3.md", None),
]

# Campaign records produced by a standalone script rather than by
# run_analysis.py: (script, argv, record). Each reads its campaign's committed
# csv.gz export when the DuckDB is absent, so this whole block rebuilds on a
# clean clone. fig18/fig19 ride along with their campaigns' scripts.
CAMPAIGN_RECORDS = [
    ("analysis_concurrency.py", [], "RESULTS_CONCURRENCY.md"),
    ("analysis_learned.py", [], "RESULTS_LEARNED.md"),
    ("analysis_risk.py", [], "RESULTS_RISK.md"),
    ("analysis_risk_budget.py", [], "RESULTS_RISK_BUDGET.md"),
    ("analysis_tenant_scale.py", [], "RESULTS_TENANT_SCALE.md"),
    ("analysis_chaos.py", [], "RESULTS_CHAOS_SIM.md"),
    ("analysis_econ.py", ["tier"], "RESULTS_TIER_RATIO.md"),
    ("analysis_econ.py", ["hk"], "RESULTS_HK_ADOPTION.md"),
    ("analysis_econ.py", ["lm"], "RESULTS_LM_ADOPTION.md"),
    ("analysis_econ.py", ["mixp95"], "RESULTS_MIXTURE_P95.md"),
    ("analysis_econ.py", ["tierwu"], "RESULTS_TIER_WU.md"),
    ("analysis_eviction_parity.py", [], "RESULTS_EVICTION_PARITY.md"),
    # Live-derived records were entirely outside this gate until session 35 —
    # the audit's D10 finding. phase7_ordinal now falls back to its committed
    # csv exports, so it rebuilds on a clean clone like every other record.
    ("analysis_order_permutation.py", [], "RESULTS_ORDER_PERMUTATION.md"),
    ("phase7_ordinal.py", [], "PHASE7_ORDINAL.md"),
    # The M3 cost separation was outside this gate entirely until session 37 —
    # guarantee.py was imported by its own test and nothing else, so the
    # paper's only formal contribution could not be regenerated by any
    # committed command. It needs no campaign data: it derives from the
    # plant constants, so it rebuilds on a clean clone unconditionally.
    ("analysis_separation.py", [], "RESULTS_SEPARATION.md"),
    ("analysis_trace_parity.py", [], "RESULTS_TRACE_PARITY.md"),
    # Both traces of the budget-parity campaign are in, so the record joins
    # the gate as PREREG_BUDGET_PARITY requires. It was deliberately held out
    # while only Azure had landed: an interim record cannot carry a
    # byte-identity guarantee it is about to break.
    ("analysis_budget_parity.py", [], "RESULTS_BUDGET_PARITY.md"),
    # WP3: the -joint-control ablation re-scored against a tier rule that is
    # not absorbing. Reads its own campaign DB, falling back to the committed
    # export, so a clean clone rebuilds it like every other record.
    ("analysis_layered_fix.py", [], "RESULTS_LAYERED_FIX.md"),
    # WP13: the coupled floor. Its V2 check FALSIFIED the first construction
    # and the record says so; it is gated anyway, because a falsified
    # derivation that cannot be regenerated is worse than no record at all.
    ("analysis_separation_mt.py", [], "RESULTS_SEPARATION_MT.md"),
    # WP6: the MPC with a wrong plant. The belief arms read their own
    # campaign DB, falling back to the committed export like every other.
    ("analysis_model_mismatch.py", [], "RESULTS_MODEL_MISMATCH.md"),
    # WP14 attempt 2: a FAILED sitting, gated like any other. It rebuilds
    # from the injector logs and run record committed under
    # eval/results/wp14_attempt2/ rather than from campaign metrics -- there
    # are none, which is the finding. A failure record that cannot be
    # regenerated is a failure record that can quietly drift.
    ("analysis_live_soak.py", [], "RESULTS_LIVE_SOAK.md"),
    # WP14 attempt 4: the 24 h sitting that completed. Gated for the same
    # reason as attempt 2, and one more -- its headline is that three of five
    # frozen hypotheses had no working instrument, two of which compute a
    # PASSING value while testing nothing. That reading is exactly the kind a
    # later edit could soften into "SK-H1 PASS, SK-H2 PASS" without anyone
    # noticing, so it is pinned byte-for-byte like every other record.
    #
    # Rebuilds from eval/results/live_soak_evidence/: the hour buckets and
    # control steps rescued from Postgres before teardown, the injector logs,
    # and the port-forward summary. Not from campaign metrics -- the DuckDB
    # timeseries table is empty by config (timeseries_reps: 0) and eval-export
    # emits no timeseries at all, which is the finding.
    ("analysis_live_soak_v2.py", [], "RESULTS_LIVE_SOAK_V2.md"),
    #
    # Attempt 5 (WP14). Rebuilds from eval/results/live_soak_evidence/ plus the
    # validation ladder's Stage B and Stage C evidence, which the record quotes
    # as preconditions. The eval-export files were extracted from the live
    # cluster after the run aborted -- the harness's own export step never ran,
    # because check_k6_delivery raises before it.
    ("analysis_live_soak_v3.py", [], "RESULTS_LIVE_SOAK_V3.md"),
    #
    # WP13 step 2. Rebuilds from guarantee.py alone -- no campaign input, no
    # hand-entered numbers. Slow on purpose: the exact ordered walk over every
    # offset vector is the whole point, and the cheap shortcut it refuses to
    # use is what S2 falsifies.
    ("analysis_separation_mt_v2.py", [], "RESULTS_SEPARATION_MT_V2.md"),
    #
    # WP13 step 3. v2 reported the eight-tenant floor NOT EVALUABLE at
    # 268,435,456 offset vectors; the vectorised ordered walk computes it in
    # ~2 h. That is affordable once and NOT affordable here, so the expensive
    # rows come from the committed `separation_mt_v3_walk.json` and this script
    # RE-DERIVES rows 1..6 at gate time and compares them (S5). A stale or
    # edited artifact therefore fails the gate rather than replaying quietly.
    # Regenerate the artifact with `python separation_mt_v3_walk.py`.
    ("analysis_separation_mt_v3.py", [], "RESULTS_SEPARATION_MT_V3.md"),
    #
    # M3. EXPLORATORY, and the record says so in its own header: the window
    # features were chosen after seeing the data, so nothing in it may be
    # quoted as a confirmed result. It is gated here anyway because it reads
    # committed per-window CSVs and must keep reproducing -- and because its
    # W1 self-check re-derives the published TP-H1 headline, so a drift in
    # either the CSVs or the record surfaces as a gate failure.
    ("analysis_window_character.py", [], "RESULTS_WINDOW_CHARACTER.md"),
    #
    # T3. Weight-free dominance over the headline matrix. Rebuilds from the
    # committed metrics_full.csv.gz, so a clean clone gets it. Gated because
    # its D1 self-check re-asserts the matrix shape (1800 runs / 6 arms /
    # 60 cells): if that export ever drifts, this fails rather than quietly
    # reporting dominance over a different experiment.
    ("analysis_dominance.py", [], "RESULTS_DOMINANCE.md"),
    #
    # L5: the first sitting where a REAL TRACE drove a REAL CLUSTER. Two
    # arms x 720 steps, demand from the simulator's own projection so the
    # two substrates cannot drift. Rebuilds from the committed
    # trace_live_runs.csv export (eval/results/*.duckdb is gitignored) plus
    # trace_live_evidence/ for the TL-H3 delivery gate, and recomputes the
    # sim side from the trace, so a clean clone gets it.
    ("analysis_trace_live.py", [], "RESULTS_TRACE_LIVE.md"),
    # W7 v2: node spread. Reads the committed load_distribution.json from the
    # sitting rather than a campaign DB - the verdicts are about placement,
    # which lives in that evidence file and nowhere else.
    # W2: whether SK-H1's frozen rule can resolve a fault at all. Reads the
    # committed attempt-10 export; descriptive, and it revises no verdict.
    ("analysis_skh1_discriminability.py", [], "RESULTS_SKH1_DISCRIMINABILITY.md"),
    ("analysis_multinode.py",
     ["--evidence", str(RESULTS / "multinode_steady_evidence")],
     "RESULTS_MULTINODE.md"),

    #
    # Attempt 6 (WP14). The first sitting to survive long enough to SCORE
    # hypotheses: 11.5M requests over 10 h 44 m, ended by a 19.5 s stall.
    # Rebuilds from eval/results/live_soak_evidence/ -- the exports were taken
    # from the live cluster after the abort, because check_k6_delivery raises
    # before the harness reaches its own export step.
    ("analysis_live_soak_v4.py", [], "RESULTS_LIVE_SOAK_V4.md"),
    #
    # Attempt 7 (WP14). The sitting that falsified the storage hypothesis:
    # fsync, full_page_writes and synchronous_commit all disabled, and the
    # worst stall grew from 19.5 s to 51.4 s.
    ("analysis_live_soak_v5.py", [], "RESULTS_LIVE_SOAK_V5.md"),
    #
    # Attempt 9 (WP14). Rebuilds from eval/results/live_soak_attempt9_evidence/
    # only -- no eval-export exists, because the delivery gate rejected the run
    # before the harness reached its export step, so SK-H1/H2/H3 are reported
    # UNSCOREABLE rather than approximated. The sitting that named the stall:
    # the V7 host-event tail caught five Kernel-Power transitions and zero
    # storage events across 14 h 33 m, and it is the first to clear the
    # design's 12 h minimum.
    ("analysis_live_soak_v7.py", [], "RESULTS_LIVE_SOAK_V7.md"),
    #
    # Attempt 10 (WP14). The first COMPLETED and first VALID sitting:
    # valid_runs 1, 24 h 00 m 11 s, 25,806,353 requests, zero dropped
    # iterations, zero pod restarts, 8 of 8 faults. Because the delivery gate
    # accepted it, eval-export ran and SK-H1/H2/H3 are scored rather than lost.
    # SK-H2 and SK-H4 pass; SK-H1 and SK-H3 fail, both on rules specified with
    # no headroom against a near-constant metric, and both are reported as
    # failures rather than repaired after the fact.
    ("analysis_live_soak_v8.py", [], "RESULTS_LIVE_SOAK_V8.md"),
    #
    # WP8b (B1, the three-knob live plane). Rebuilds from
    # eval/results/wave4_live_plane_evidence/ and wp8b_substrate_evidence/.
    # There are no run metrics because there are no valid runs: WL-H2's
    # knob-liveness gate returned SUBSTRATE INADEQUATE and WL-H1 is void, which
    # is the outcome PREREG_WAVE4_LIVE_PLANE registers for an inert knob. The
    # record is built from the gate's own report plus the tunnel preflight that
    # rules out the free split-host route as the cause.
    ("analysis_wave4_live_plane.py", [], "RESULTS_WAVE4_LIVE_PLANE.md"),
]

CORE_EXPORTS = ["metrics_full.csv.gz", "metrics_ablations.csv.gz",
                "metrics_forecasters.csv.gz", "metrics_realism.csv.gz"]
DEPS = ["duckdb", "pandas", "scipy", "statsmodels", "matplotlib"]


def check_inputs() -> tuple[list[str], list[str]]:
    """Returns (problems, notices). Problems block the git tier."""
    problems, notices = [], []
    for name in CORE_EXPORTS:
        if not (RESULTS / name).exists():
            problems.append(f"missing committed export: eval/results/{name}")
    for mod in DEPS:
        try:
            __import__(mod)
        except ImportError:
            problems.append(f"missing python package: {mod} "
                            "(pip install -r eval/requirements.txt)")
    for record, db in RECORDS:
        if db and not (RESULTS / db).exists():
            notices.append(f"{record}: needs eval/results/{db} "
                           "(Zenodo archive) — will be skipped")
    if not (RESULTS / "raw_sim.duckdb").exists():
        notices.append("fig09_adaptation_trace: needs raw_sim.duckdb "
                       "(timeseries live only in the archive) — will be skipped")
    return problems, notices


def diff_record(name: str, out_dir: Path) -> str:
    committed, rebuilt = ANALYSIS / name, out_dir / name
    if not rebuilt.exists():
        return "skipped (needs archive)" if not_available(name) else "NOT PRODUCED"
    if not committed.exists():
        return "no committed version to compare"
    # Bytes, not splitlines(). The check here used to compare
    # `.splitlines()` lists while reporting MATCH (byte-identical), which
    # claimed more than it verified in two ways: splitlines() erases the
    # presence of a final newline entirely, and it also splits on form
    # feed and the Unicode separators. What it did do -- absorb the CRLF
    # that Path.write_text emits on Windows against the LF that
    # .gitattributes checks out everywhere -- is kept, but as an explicit
    # and auditable newline canonicalisation rather than as a side effect.
    raw_committed, raw_rebuilt = committed.read_bytes(), rebuilt.read_bytes()
    if raw_committed == raw_rebuilt:
        return "MATCH (byte-identical)"
    canon_committed = raw_committed.replace(CRLF, LF)
    canon_rebuilt = raw_rebuilt.replace(CRLF, LF)
    if canon_committed == canon_rebuilt:
        return "MATCH (identical; CRLF vs LF only)"
    a = canon_committed.decode("utf-8").split(chr(10))
    b = canon_rebuilt.decode("utf-8").split(chr(10))
    delta = [ln for ln in difflib.unified_diff(a, b, lineterm="")
             if ln[:1] in "+-" and ln[:3] not in ("+++", "---")]
    (out_dir / f"diff_{name}.txt").write_text(
        "\n".join(difflib.unified_diff(a, b, f"committed/{name}",
                                       f"rebuilt/{name}", lineterm="")),
        encoding="utf-8")
    return f"drift: {len(delta)} changed lines (see diff_{name}.txt)"


# matplotlib stamps /CreationDate and /ModDate into every PDF it writes, so a
# PDF can never be byte-identical across two runs however deterministic the
# plot is. Stripping exactly those two keys is the whole normalisation: on the
# session-43 audit all 19 PDFs matched after it, and all 19 PNGs matched with
# no normalisation at all.
_PDF_TIMESTAMPS = re.compile(rb"/(CreationDate|ModDate)\s*\([^)]*\)")


def figure_bytes(path: Path) -> bytes:
    raw = path.read_bytes()
    return _PDF_TIMESTAMPS.sub(b"", raw) if path.suffix == ".pdf" else raw


CONTENT = "content"


def compare_figure_content(fig_dir: Path) -> tuple[list[tuple[str, str]], int]:
    """What each figure PLOTS, against the committed dump of the same.

    This is the check that can run anywhere. `figures.save()` writes a
    canonical JSON of every line, bar, scatter offset, scale, limit, tick
    label and legend entry next to each figure, and that artifact does not
    depend on the local font stack -- so a reviewer on Linux verifies the same
    property the author verified on Windows, which the byte comparison below
    cannot deliver and never could.
    """
    drifted: list[tuple[str, str]] = []
    rebuilt_dir = fig_dir / CONTENT
    checked = 0
    for rebuilt in sorted(rebuilt_dir.glob("fig*.json")):
        checked += 1
        committed = FIGURES / CONTENT / rebuilt.name
        if not committed.exists():
            drifted.append((rebuilt.name, "no committed content to compare"))
            continue
        if committed.read_bytes() != rebuilt.read_bytes():
            drifted.append((rebuilt.name, content_diff(committed, rebuilt)))
    return drifted, checked


def content_diff(committed: Path, rebuilt: Path) -> str:
    """Name the first field that moved, so drift is diagnosable from the log
    rather than only detectable."""
    a = committed.read_text(encoding="utf-8").splitlines()
    b = rebuilt.read_text(encoding="utf-8").splitlines()
    for line in difflib.unified_diff(a, b, n=0, lineterm=""):
        if line.startswith(("-", "+")) and not line.startswith(("---", "+++")):
            return f"plots different data, first change: {line.strip()[:90]}"
    return "plots different data"


def renderer_note() -> tuple[bool, str]:
    """Whether this machine rasterises the way the committed files were drawn.

    The PDF/PNG comparison is exact and worth keeping where it applies, but it
    only applies here. `figures.save()` uses bbox_inches="tight", which sizes
    the output from rendered text extents, so a different font stack changes
    every byte without changing a single plotted number.
    """
    stamp = FIGURES / CONTENT / "rendered_on.json"
    here = version("matplotlib")
    if not stamp.exists():
        return False, "no renderer stamp"
    info = json.loads(stamp.read_text(encoding="utf-8"))
    there = info.get("matplotlib")
    if info.get("platform") == sys.platform and there == here:
        return True, f"same renderer: {sys.platform}, matplotlib {here}"
    return False, (f"drawn on {info.get('platform')}/matplotlib {there}, "
                   f"here {sys.platform}/matplotlib {here} -- not comparable")


def compare_figures(fig_dir: Path) -> list[tuple[str, str]]:
    """Every rebuilt figure against its committed copy.

    Until session 43 this did not exist: the gate counted how many figures
    were REBUILT and never once compared them, so all nineteen could have
    changed — different data, different axes, a different result — and it
    would still have printed 19/19 and passed. The records were verified
    byte-identically; the figures that visualise those records were not
    verified at all, and the thesis cites them.
    """
    drifted: list[tuple[str, str]] = []
    for rebuilt in sorted(fig_dir.glob("fig*")):
        if rebuilt.suffix not in (".pdf", ".png"):
            continue
        committed = FIGURES / rebuilt.name
        if not committed.exists():
            drifted.append((rebuilt.name, "no committed copy to compare"))
            continue
        if figure_bytes(committed) != figure_bytes(rebuilt):
            drifted.append((rebuilt.name, "content differs"))
    return drifted


def not_available(record: str) -> bool:
    db = dict(RECORDS).get(record)
    return bool(db) and not (RESULTS / db).exists()


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true",
                    help="verify inputs and dependencies, print the plan, exit")
    ap.add_argument("--out", type=Path, default=REPO_ROOT / "reproduce_out",
                    help="scratch output directory (default: reproduce_out/)")
    args = ap.parse_args()

    problems, notices = check_inputs()
    tier = "archive" if (RESULTS / "raw_sim.duckdb").exists() else "git"
    print(f"tier: {tier}")
    for n in notices:
        print(f"  note: {n}")
    for p in problems:
        print(f"  PROBLEM: {p}")
    if args.check:
        print("check", "FAILED" if problems else "OK")
        return 1 if problems else 0
    if problems:
        return 1

    out_dir = args.out.resolve()
    fig_dir = out_dir / "figures"
    fig_dir.mkdir(parents=True, exist_ok=True)
    # Clear this script's own artifacts from a previous run before rebuilding.
    # Without it, anything that fails to rebuild now is still counted from the
    # last run's leftovers — which overstates exactly the claim this script
    # exists to substantiate. (Only known artifact patterns are removed, never
    # the directory itself: --out can point anywhere.)
    stale = 0
    for pattern in ("fig*.pdf", "fig*.png", "FIGURES.md"):
        for path in fig_dir.glob(pattern):
            path.unlink()
            stale += 1
    for pattern in ("*.md", "diff_*.txt"):
        for path in out_dir.glob(pattern):
            path.unlink()
            stale += 1
    if stale:
        print(f"cleared {stale} artifact(s) from the previous run")
    env = {**os.environ,
           "POLYFORGE_ANALYSIS_OUT": str(out_dir),
           "POLYFORGE_FIG_DIR": str(fig_dir)}
    print(f"rebuilding into {out_dir} ...")
    proc = subprocess.run([sys.executable, "run_analysis.py"],
                          cwd=ANALYSIS, env=env)
    if proc.returncode != 0:
        print("run_analysis.py FAILED")
        return proc.returncode

    # Campaign scripts, each in its own process so one failure cannot take the
    # rest of the report with it.
    failed_campaigns = []
    for script, argv, record in CAMPAIGN_RECORDS:
        proc = subprocess.run([sys.executable, script, *argv], cwd=ANALYSIS,
                              env=env, capture_output=True, text=True)
        if proc.returncode != 0:
            failed_campaigns.append((record, proc.stderr.strip().splitlines()[-1:]))

    print("\n=== reproduction report ===")
    all_records = [r for r, _ in RECORDS] + [r for _, _, r in CAMPAIGN_RECORDS]
    width = max(len(r) for r in all_records)
    matched, exact = 0, 0
    for record, _ in RECORDS:
        status = diff_record(record, out_dir)
        matched += status.startswith("MATCH")
        exact += status == "MATCH (byte-identical)"
        print(f"  {record:<{width}} {status}")
    for _, _, record in CAMPAIGN_RECORDS:
        status = diff_record(record, out_dir)
        matched += status.startswith("MATCH")
        exact += status == "MATCH (byte-identical)"
        print(f"  {record:<{width}} {status}")
    print(f"  {'records':<{width}} {matched}/{len(all_records)} identical "
          f"-- {exact} byte-for-byte, {matched - exact} differing only in "
          f"line endings (Path.write_text emits CRLF on Windows; "
          f".gitattributes checks out LF everywhere)")
    for record, err in failed_campaigns:
        print(f"    campaign script for {record} exited nonzero: "
              f"{' '.join(err) or 'see output above'}")

    rebuilt_figs = sorted(p.stem for p in fig_dir.glob("fig*.pdf"))
    committed_figs = sorted(p.stem for p in FIGURES.glob("fig*.pdf"))
    missing = [f for f in committed_figs if f not in rebuilt_figs]
    print(f"  {'figures':<{width}} {len(rebuilt_figs)}/{len(committed_figs)} "
          f"rebuilt as vector PDF + 600-DPI PNG")

    # The gating check: what the figures plot. Platform-independent, so it
    # fails in CI on Linux as readily as on the machine that drew them.
    content_drift, content_n = compare_figure_content(fig_dir)
    if rebuilt_figs and not content_n:
        # Otherwise the dump mechanism could stop emitting entirely and
        # this check would pass on an empty set -- which is the defect
        # R8 found in the figure step it replaced.
        content_drift.append(("figures/content",
                              "no content dumps were produced at all"))
    print(f"  {'figure content':<{width}} "
          f"{content_n - len(content_drift)}/{content_n} plot identical data")
    for name, why in content_drift:
        print(f"    DRIFT: {name} ({why})")

    # The strengthening check: the rendered files themselves. Exact where
    # the renderer matches, meaningless where it does not, reported either
    # way rather than quietly dropped.
    fig_drift = compare_figures(fig_dir)
    same_renderer, renderer = renderer_note()
    fig_n = len(rebuilt_figs) * 2
    print(f"  {'figure files':<{width}} "
          f"{fig_n - len(fig_drift)}/{fig_n} byte-identical -- {renderer}")
    if fig_drift and not same_renderer:
        print(f"    {len(fig_drift)} rendered file(s) differ; not a failure "
              f"on a different renderer, and the content check above is "
              f"what holds these figures to their data")
    for name, why in (fig_drift if same_renderer else []):
        print(f"    DRIFT: {name} ({why})")
    for f in missing:
        if tier == "git" or f == "fig09_adaptation_trace":
            print(f"    not rebuilt: {f} (needs archive timeseries)")
        else:
            print(f"    not rebuilt: {f}")
    print("committed records and figures were not modified.")

    # Exit status must carry the verdict. This previously returned 0
    # unconditionally, so a CI job or a reviewer running `python
    # scripts/reproduce.py` saw green while every record drifted and every
    # campaign script crashed — the gate reported failure only in prose.
    drifted = len(all_records) - matched
    raster_fail = fig_drift if same_renderer else []
    if drifted or failed_campaigns or content_drift or raster_fail:
        print(f"\nFAILED: {drifted} record(s) not byte-identical, "
              f"{len(failed_campaigns)} campaign script(s) exited nonzero, "
              f"{len(content_drift)} figure(s) plotting different data, "
              f"{len(raster_fail)} figure file(s) not identical on a "
              f"matching renderer.")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
