"""PREREG_RETUNED.md -> RESULTS_RETUNED.md: the composite objective against
the FAIR_J comparators re-tuned per cluster size, on fresh shared seeds.

FROZEN with the pre-registration; not edited after the run. The test is the
one PREREG_FAIR_J froze, imported from its (equally frozen) scorer, so the
two campaigns are judged by identical code.

    python analysis_retuned.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
from analysis_fair_j import (  # noqa: E402
    BOOT_N, BOOT_SEED, DESIGN, NI_MARGIN, TREATMENT, complete_design_points, design_diffs,
    noninferior, score, superiority,
)
from stats import composite_objective, record_path  # noqa: E402

RESULTS = HERE.parents[1] / "eval" / "results"
DB = RESULTS / "raw_sim_retuned.duckdb"
CSV = RESULTS / "metrics_matrix_retuned.csv.gz"
RECORD = "RESULTS_RETUNED.md"
PRIMARY = {"RT-H1": "hpa_fair_retuned", "RT-H2": "keda_fair_retuned",
           "RT-H3": "jcac_nojoint_v2_retuned"}
PUBLISHED = {"hpa_fair_retuned": "hpa_fair", "keda_fair_retuned": "keda_fair"}
ARMS = [TREATMENT, *PRIMARY.values(), *PUBLISHED.values()]
SIZES = ["small", "medium", "large"]
COLUMNS = ["system", "workload", "tenant_mix", "cluster_size", "rep", "total_cost_usd",
           "mean_violation", "mean_jain", "mean_excess", "tier_none_step_share"]


def load() -> pd.DataFrame:
    if DB.exists():
        import duckdb

        con = duckdb.connect(str(DB), read_only=True)
        try:
            return con.execute(
                "select r.system, r.workload, r.tenant_mix, r.cluster_size, r.rep, "
                "m.total_cost_usd, m.mean_violation, m.mean_jain, m.mean_excess, "
                "m.tier_none_step_share from runs r join metrics m on r.run_id = m.run_id "
                "where r.status = 'valid'").fetchdf()
        finally:
            con.close()
    return pd.read_csv(CSV, float_precision="round_trip")[COLUMNS]


def prepare(df: pd.DataFrame) -> pd.DataFrame:
    df = complete_design_points(df, ARMS)
    return df.assign(J=composite_objective(df))


def direction(r: dict) -> str:
    """Registered reading of a comparison's CI (PREREG_RETUNED, outcomes)."""
    if r["ci"][1] < 0:
        return "treatment better"
    if r["ci"][0] > 0:
        return "comparator better"
    return "no difference shown"


def build(df: pd.DataFrame) -> str:
    n_all = df[DESIGN].drop_duplicates().shape[0]
    df = prepare(df)
    n_dp = df[DESIGN].drop_duplicates().shape[0]
    prim = score(df, PRIMARY)
    L = ["# Composite objective against per-size re-tuned comparators, fresh shared seeds", "",
         "Generated by `analysis_retuned.py`, frozen with `PREREG_RETUNED.md`. Treatment "
         f"`{TREATMENT}`; comparators re-tuned per cluster size on the tuning slice "
         "(`eval/baselines/tuned_arms.yaml`). Unit: the design point (reps averaged); "
         f"{n_dp} of {n_all} design points complete for every arm (listwise rule). A PASS needs the "
         "one-sided Wilcoxon p at or below its Holm threshold AND the 95% bootstrap CI of the mean "
         f"difference entirely below 0 ({BOOT_N:,} resamples, seed {BOOT_SEED}); the PREREG_FAIR_J "
         "rule, imported from its scorer. Negative = the treatment is better.", "",
         "## Per-arm means", "",
         "| arm | J | cost $ | mean_violation | mean_excess | Jain | AI shed (tier=none) |",
         "|---|---:|---:|---:|---:|---:|---:|"]
    for arm in ARMS:
        s = df[df.system == arm]
        L.append(f"| `{arm}` | {s.J.mean():.4f} | {s.total_cost_usd.mean():.4f} | {s.mean_violation.mean():.4f} | "
                 f"{s.mean_excess.mean():.4f} | {s.mean_jain.mean():.4f} | {s.tier_none_step_share.mean():.1%} |")
    L += ["", "## Confirmatory: RT-H1..H3 (one Holm family of 3)", "",
          "| id | vs | design points | ΔJ | d_z | 95% CI of ΔJ | treatment better in | Wilcoxon p | "
          "Holm threshold | verdict | direction |", "|---|---|---:|---:|---:|---|---:|---:|---:|---|---|"]
    for hid, r in prim.items():
        L.append(f"| **{hid}** | `{PRIMARY[hid]}` | {r['n']} | {r['mean']:+.4f} | {r['dz']:+.2f} | "
                 f"[{r['ci'][0]:+.4f}, {r['ci'][1]:+.4f}] | {r['better']:.0%} | {r['p']:.3g} | "
                 f"{r['threshold']:.4f} | {'PASS' if r['pass'] else 'FAIL'} | {direction(r)} |")
    L += ["", "## SLO guard: `mean_excess` non-inferiority (one-sided 95% bootstrap bound < "
          f"{NI_MARGIN})", "", "| guard | vs | mean diff | 95% upper bound | verdict |", "|---|---|---:|---:|---|"]
    for hid, comp in PRIMARY.items():
        g = noninferior(design_diffs(df, TREATMENT, comp, "mean_excess"))
        L.append(f"| {hid}-NI | `{comp}` | {g['mean']:+.4f} | {g['ucb']:+.4f} | "
                 f"{'PASS' if g['ni'] else 'FAIL'} |")
    L += ["", "## Per cluster size (descriptive; the tuning slice predicted a size split)", "",
          "| cluster | vs | design points | ΔJ | 95% CI | direction |", "|---|---|---:|---:|---|---|"]
    for size in SIZES:
        sub = df[df.cluster_size == size]
        for comp in PRIMARY.values():
            r = superiority(design_diffs(sub, TREATMENT, comp, "J"))
            L.append(f"| {size} | `{comp}` | {r['n']} | {r['mean']:+.4f} | "
                     f"[{r['ci'][0]:+.4f}, {r['ci'][1]:+.4f}] | {direction(r)} |")
    L += ["", "## What re-tuning bought the comparators (descriptive)", "",
          "| re-tuned − as published | ΔJ | 95% CI |", "|---|---:|---|"]
    for new, old in PUBLISHED.items():
        r = superiority(design_diffs(df, new, old, "J"))
        L.append(f"| `{new}` − `{old}` | {r['mean']:+.4f} | [{r['ci'][0]:+.4f}, {r['ci'][1]:+.4f}] |")
    L += ["", f"## Beside it: the treatment against the as-published comparators (descriptive)", "",
          "| vs | ΔJ | 95% CI | direction |", "|---|---:|---|---|"]
    for comp in PUBLISHED.values():
        r = superiority(design_diffs(df, TREATMENT, comp, "J"))
        L.append(f"| `{comp}` | {r['mean']:+.4f} | [{r['ci'][0]:+.4f}, {r['ci'][1]:+.4f}] | {direction(r)} |")
    L += ["", "## Per workload, treatment vs each primary comparator (descriptive)", "",
          "| workload | vs | ΔJ | treatment better in |", "|---|---|---:|---:|"]
    for comp in PRIMARY.values():
        ma = df[df.system == TREATMENT].groupby(DESIGN).J.mean()
        mb = df[df.system == comp].groupby(DESIGN).J.mean()
        d = (ma - mb).dropna()
        for wl, sub in d.groupby(level="workload"):
            L.append(f"| `{wl}` | `{comp}` | {sub.mean():+.4f} | {int((sub < 0).sum())}/{len(sub)} |")
    L.append("")
    return "\n".join(L) + "\n"


def main() -> int:
    out = record_path(RECORD)
    out.write_text(build(load()), encoding="utf-8")
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
