"""WP8b (B1, the three-knob live plane) -> RESULTS_WAVE4_LIVE_PLANE.md.

Pre-registration: `PREREG_WAVE4_LIVE_PLANE.md`.

B1 IS STILL UNSCORED, BUT NOT FOR THE REASON FIRST RECORDED. The first sitting
returned SUBSTRATE INADEQUATE and this record said the knobs were inert. That
verdict was a FALSE NEGATIVE: the WL-H2 probe was racing the operator's Policy
reconciler, which pushes each Policy's cache and tier levers to the very admin
endpoint the probe drives. With the reconciler paused for the probe, WL-H2
PASSES and both knobs are demonstrably live.

What blocks B1 now is a different and genuine limitation: the free split-host
route cannot carry the frozen cell's CONCURRENT load. Sequential probes pass;
k6 at ~218 virtual users drives 48% of requests into a 60 s timeout, and the
delivery threshold aborts the run at 20% of the load window.

Both readings are committed under `wp8b_substrate_evidence/` so the correction
is checkable rather than asserted. No margin has been lowered at any point.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from stats import record_path  # noqa: E402

REPO = Path(__file__).resolve().parents[2]
SUB = REPO / "eval" / "results" / "wp8b_substrate_evidence"


def read(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def build() -> str:
    L: list[str] = []
    def w(s: str = "") -> None:
        L.append(s)

    knob = read(SUB / "knob_preflight_operator_paused.json")
    raced = read(SUB / "knob_preflight_ordered.json")
    k6 = read(SUB / "k6-summary_concurrency_failure.json")["metrics"]
    tunnel = read(SUB / "tunnel_preflight_session41b.json")

    cache, tier = knob["cache"], knob["tier"]
    rcache, rtier = raced["cache"], raced["tier"]
    failed_pct = float(k6["http_req_failed"]["value"]) * 100.0
    failed_n = int(k6["http_req_failed"]["passes"])
    reqs = int(k6["http_reqs"]["count"])
    worst_ms = float(k6["iteration_duration"]["max"])
    med_ms = float(k6["iteration_duration"]["med"])

    w("# B1 — the three-knob live plane: the knobs are LIVE, the free route "
      "cannot carry the load (WP8b)")
    w()
    w("Generated by `analysis_wave4_live_plane.py` from evidence committed "
      "under `eval/results/wp8b_substrate_evidence/`. Pre-registration: "
      "`PREREG_WAVE4_LIVE_PLANE.md`.")
    w()
    w()
    w("## Headline")
    w()
    w("**WL-H1 is still unscored, and the reason has changed.** The 4 arms x 4 "
      "cells matrix has not been run to completion. But the first recorded "
      "cause — inert knobs — was wrong, and this record corrects it.")
    w()
    w(f"With the operator's Policy reconciler paused for the probe, **WL-H2 "
      f"PASSES**: `{knob['verdict']}`. Both knobs move the substrate, and the "
      "tier pin is exclusive in both directions.")
    w()
    w("What blocks the matrix instead is throughput. Under the frozen cell's "
      f"concurrency, **{failed_pct:.1f}% of requests failed** "
      f"({failed_n:,} of {reqs:,}) and k6's delivery threshold aborted the run "
      "at 20% of the load window.")
    w()
    w()
    w("## The correction: SUBSTRATE INADEQUATE was a false negative")
    w()
    w("The WL-H2 probe drives `PUT /admin/tenants/{id}/knobs`. So does the "
      "operator: `PolicyReconciler.Reconcile` pushes each Policy's cache and "
      "tier levers to that exact endpoint "
      "(`internal/operator/controllers/gateway_knobs.go:49`, called from "
      "`policy_controller.go:106`). The failing arm was `jcac`, which is in "
      "`OPERATOR_SYSTEMS`, so the reconciler was live throughout the probe.")
    w()
    w("Probe and operator fought over one knob. The same measurement, with and "
      "without the reconciler running:")
    w()
    w("| criterion | reconciler RUNNING | reconciler PAUSED |")
    w("|---|---|---|")
    w(f"| cache hit @64 MB vs @0 MB | {rcache['hit_rate_budgeted']:.2f} vs "
      f"**{rcache['hit_rate_zero']:.2f}** (delta {rcache['delta']:.2f}) | "
      f"{cache['hit_rate_budgeted']:.2f} vs **{cache['hit_rate_zero']:.2f}** "
      f"(delta {cache['delta']:.2f}) |")
    w(f"| cache live (margin {cache['margin']}) | **{rcache['live']}** | "
      f"**{cache['live']}** |")
    w(f"| pinned `small` served | {rtier['tiers_seen_a']} | "
      f"**{tier['tiers_seen_a']}** |")
    w(f"| pinned `mid` served | **{rtier['tiers_seen_b']}** | "
      f"**{tier['tiers_seen_b']}** |")
    w(f"| `routing_moved` | **{rtier['routing_moved']}** | "
      f"**{tier['routing_moved']}** |")
    w(f"| `latency_moved` | {rtier['latency_moved']} | "
      f"**{tier['latency_moved']}** |")
    w(f"| verdict | SUBSTRATE INADEQUATE | **WL-H2 PASS** |")
    w()
    w("One mechanism explained every failing criterion. The probe pinned "
      "`mid`; the next reconcile wrote the Policy's tier back; the probe "
      "observed both tiers. The asymmetry followed too — the reconciler's own "
      "value wins, so pinning *that* tier looked exclusive while pinning the "
      "other leaked. The cache read the same way: the probe set "
      "`cache_size_mb=0`, the reconciler wrote the Policy's size back, and the "
      f"hit rate at \"0 MB\" came out {rcache['hit_rate_zero']:.2f} instead of "
      f"{cache['hit_rate_zero']:.2f}.")
    w()
    w("**The gateway was never at fault.** "
      "`TestTierPinIsExclusiveAcrossManyRequests` pins each tier, sends the "
      "same eight requests the probe does, and asserts the pin holds for every "
      "one; it passes. The pre-existing `TestTierKnobMovesRoutingAndTelemetry` "
      "sends **one** request per tier, which is why an intermittent leak "
      "survived it.")
    w()
    w("**The fix** pauses the reconciler for the probe and restores it "
      "immediately after (`_operator_paused`). WL-H2 measures the *substrate*, "
      "not the arm's controller. The probe runs before the load window, so no "
      "scored behaviour changes.")
    w()
    w()
    w("## What actually blocks the matrix now")
    w()
    w("With the gate passed, the run proceeded to load and failed there:")
    w()
    w("| | |")
    w("|---|---:|")
    w(f"| requests | {reqs:,} |")
    w(f"| **failed** | **{failed_pct:.1f}%** ({failed_n:,}) |")
    w(f"| iteration duration median | {med_ms:.0f} ms |")
    w(f"| iteration duration max | **{worst_ms / 1000:.0f} s** |")
    w("| load window completed | **20%** (1 m 01 s of 5 m 10 s) |")
    w("| aborted by | `http_req_failed` threshold `rate<0.01` |")
    w()
    w("The shape is the diagnosis. The median request is fast — cache hits and "
      "CRUD — while the tail sits exactly on a **60 second timeout**. A free "
      "Kaggle P100 serialises generation, so the frozen cell's ~218 concurrent "
      "virtual users queue behind one GPU until they time out.")
    w()
    w("**This is why the tunnel preflight could not catch it.** "
      "`tunnel_preflight.py` issues **sequential** probes — eight per tier — "
      "and measures round-trip latency. It cannot observe queueing, because it "
      "never creates any. On this session's route it reported:")
    w()
    w(f"- tier gap **{tunnel['delta_ms']:.1f} ms** vs "
      f"{tunnel['threshold_ms']:.1f} ms threshold — material")
    w(f"- slowest tier {tunnel['slowest_tier_mean_ms']:.0f} ms against a "
      f"{tunnel['ai_slo_premium_ms']:.0f} ms premium SLO — only "
      f"**{tunnel['slo_headroom_ms']:.0f} ms** of headroom")
    w(f"- verdict **{tunnel['verdict']}**")
    w()
    w("A sequential preflight that passes therefore does **not** license a "
      "concurrent matrix. That is a limitation of the free split-host route "
      "which `docs/WAVE4_FREE_ROUTE.md` does not currently state, and it "
      "should: the route's own quota table discusses GPU-hours and round-trip "
      "latency, never throughput under load.")
    w()
    w()
    w("## Five harness defects, all found by running this path for the first "
      "time")
    w()
    w("`POLYFORGE_EVAL_LIVE_AI=1` had never been set on a real run — WP8b was "
      "gated on a GPU the project did not have, and WP8a deliberately runs "
      "with it unset. So none of this code had ever executed:")
    w()
    w("| defect | effect |")
    w("|---|---|")
    w("| `NameError: EVAL_DIR` in `run_knob_preflight` | the gate could not "
      "launch; all 16 runs failed identically |")
    w("| `UnicodeEncodeError` printing the gate's own output | the gate "
      "crashed reporting its verdict, through cp1252 |")
    w("| `knob_preflight.json` written into a `TemporaryDirectory` | the "
      "verdict's evidence self-deleted — the loss that took attempt 2's k6 "
      "summary |")
    w("| tiers ordered **alphabetically**, not by capability | "
      "`sorted([\"small\",\"mid\"])` inverted the probe's ascending-capability "
      "convention and **manufactured** an `ordering_correct: false` |")
    w("| the probe raced the operator's reconciler | **manufactured the "
      "SUBSTRATE INADEQUATE verdict itself** |")
    w()
    w("The last two are the serious ones: each was producing a failure that "
      "was an artefact of the apparatus rather than a property of the system "
      "under test. A pre-registered gate is only as trustworthy as the first "
      "time it is actually executed.")
    w()
    w()
    w("## What this does and does not license")
    w()
    w("**Does not:** any WL-H1 claim. There are no valid runs, and no arm "
      "comparison, cost figure or fairness number from this experiment exists "
      "or may be quoted.")
    w()
    w("**Does:** the finding that both knobs are live on this build, evidenced "
      "by a passing WL-H2 with the tier pin exclusive in both directions and a "
      "cache delta of "
      f"{cache['delta']:.2f}. The earlier inert-knob reading is withdrawn.")
    w()
    w("**Also does:** the finding that a free serialising GPU cannot carry "
      "this cell's concurrency, and that a sequential preflight cannot detect "
      "that. Both belong in the route documentation before anyone spends "
      "another session on it.")
    w()
    w("Scoring B1 needs a substrate that serves the cell's concurrency — a "
      "rented GPU, a smaller frozen cell under a NEW pre-registration, or "
      "batched serving on the free pool. The prereg's cell is frozen, so the "
      "second option is a different experiment, not an adjustment to this one.")
    w()
    return "\n".join(L) + "\n"


def main() -> int:
    out = record_path("RESULTS_WAVE4_LIVE_PLANE.md")
    out.write_text(build(), encoding="utf-8")
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
