#!/usr/bin/env python3
"""PREREG_MODEL_MISMATCH.md -> RESULTS_MODEL_MISMATCH.md.

Answers the structural question every MPC paper is asked and this repository
had never run: what happens when the controller's model is wrong?

`controller.py::_project` calls the same `evaluate_step` the engine scores
with, so with realism flags off the controller knows the true tier prices,
the true replica capacity and the true cache curve — and every sensitivity
campaign moves world and beliefs together. `belief_scale` breaks that
coupling inside the projection only; the plant is untouched, so a plan made
under a wrong belief is still scored by the true world.

Every decision rule here is fixed by the pre-registration, which was
committed and pushed before the campaign ran (`d5101c1`): the arms, the
±25% band, the 0.05 non-inferiority margin, the Holm family of twelve, the
all-six rule and the one-sided directions.

    python analysis_model_mismatch.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import duckdb
import pandas as pd
import scipy.stats as sps

sys.path.insert(0, str(Path(__file__).resolve().parent))
from stats import holm_bonferroni, record_path  # noqa: E402

_RESULTS = Path(__file__).resolve().parents[2] / "eval" / "results"
DB = _RESULTS / "raw_sim_model_mismatch.duckdb"
CSV = _RESULTS / "metrics_matrix_model_mismatch.csv.gz"

CELL = ["workload", "tenant_mix", "cluster_size", "rep"]
TENANTS = 8
COST_SCALE = 0.01
NI_MARGIN = 0.05          # inherited from PREREG_EVICTION_PARITY

# The frozen ladder. `None` marks the control, which carries no belief.
CONSTANTS = {
    "replica_capacity": "cap",
    "tier_cost": "tier",
    "cache_half": "cache",
}
LADDER = [0.5, 0.75, 1.0, 1.25, 2.0]
BAND = [0.75, 1.25]       # the +/-25% band MM-H1 and MM-H2 are scored at


def arm_for(short: str, scale: float) -> str:
    if scale == 1.0:
        return "jcac"
    tag = str(scale).replace("0.", "").replace(".", "")
    return f"jcac_belief_{short}{tag}"


def load() -> pd.DataFrame:
    cols = ("r.system, r.workload, r.tenant_mix, r.cluster_size, r.rep, "
            "m.total_cost_usd, m.mean_violation, m.mean_jain, "
            "m.cache_hit_rate, m.mean_excess, m.steps")
    if DB.exists():
        con = duckdb.connect(str(DB), read_only=True)
        df = con.execute(f"select {cols} from runs r join metrics m "
                         "on r.run_id = m.run_id where r.status = 'valid'").fetchdf()
        con.close()
    elif CSV.exists():
        df = pd.read_csv(CSV, float_precision="round_trip")
    else:
        raise FileNotFoundError(f"{DB.name} missing and export {CSV.name} absent")
    df["J"] = (df.total_cost_usd / (119 * TENANTS) / COST_SCALE
               + 2.0 * df.mean_violation + 0.5 * (1.0 - df.mean_jain))
    return df


def paired(df: pd.DataFrame, treat: str, base: str, metric: str,
           shift: float = 0.0) -> dict:
    """One-sided paired Wilcoxon of (treat - base - shift) over matched
    cells. Identical machinery to WP1/WP3/WP15 on purpose."""
    m = df[df.system == treat].merge(df[df.system == base], on=CELL,
                                     suffixes=("_t", "_b"))
    diff = (m[f"{metric}_t"] - m[f"{metric}_b"]).dropna()
    n = int(len(diff))
    mean_diff = float(diff.mean()) if n else 0.0
    base_mean = float(df[df.system == base][metric].mean())
    rel = mean_diff / base_mean if base_mean else 0.0
    shifted = diff - shift
    if n < 2 or shifted.abs().sum() == 0.0:
        return {"n": n, "mean_diff": mean_diff, "rel": rel, "p": 1.0,
                "dz": 0.0, "t_p": 1.0}
    _, p = sps.wilcoxon(shifted, alternative="less")
    _, t_p = sps.ttest_1samp(diff, 0.0)
    sd = float(diff.std(ddof=1))
    return {"n": n, "mean_diff": mean_diff, "rel": rel, "p": float(p),
            "dz": (mean_diff / sd) if sd else 0.0, "t_p": float(t_p)}


def main() -> None:
    df = load()
    L: list[str] = []
    w = L.append

    w("# The MPC with a wrong plant — model-mismatch campaign (V-series)\n")
    w("Generated by `analysis_model_mismatch.py` from "
      "`raw_sim_model_mismatch.duckdb`. Pre-registration: "
      "`PREREG_MODEL_MISMATCH.md`, committed and pushed before the campaign "
      "ran.\n")
    w("**Why this record exists.** `controller.py::_project` calls the same "
      "`model.evaluate_step` the engine scores with, so with the realism "
      "flags off the controller's model is *bit-identical to the plant*. "
      "`model.py:144-147` says as much: an override \"moves the world and "
      "every controller's beliefs together\". Until this campaign the "
      "repository contained no experiment in which the controller was wrong "
      "about anything, which makes \"it was tuned on its own simulator\" the "
      "sharpest available attack on every result in `RESULTS_MASTER.md`.\n")
    w("`belief_scale` breaks the coupling **inside the projection only**. The "
      "plant is untouched, so a plan made under a wrong belief is still "
      "scored by the true world — which is the entire experiment.\n")

    # --- the ladder --------------------------------------------------------
    w("\n## Per-arm summary (mean over the 100 matched cells)\n")
    cols = ["total_cost_usd", "mean_violation", "mean_excess", "mean_jain", "J"]
    w("\n| constant | belief | " + " | ".join(cols) + " |")
    w("|---|---:|" + "---:|" * len(cols))
    for const, short in CONSTANTS.items():
        for scale in LADDER:
            arm = arm_for(short, scale)
            sub = df[df.system == arm]
            if sub.empty:
                continue
            label = "**1.0 (control)**" if scale == 1.0 else f"{scale}"
            w(f"| `{const}` | {label} | "
              + " | ".join(f"{float(sub[c].mean()):.4g}" for c in cols) + " |")
    for arm in ("hpa_fair", "keda_fair"):
        sub = df[df.system == arm]
        if not sub.empty:
            w(f"| `{arm}` | — | "
              + " | ".join(f"{float(sub[c].mean()):.4g}" for c in cols) + " |")

    # --- MM-H1 / MM-H2, one Holm family of twelve --------------------------
    tests: dict[str, dict] = {}
    meta: dict[str, tuple[str, float, str]] = {}
    for const, short in CONSTANTS.items():
        for scale in BAND:
            arm = arm_for(short, scale)
            h1 = f"MM-H1[{short}{scale}]"
            h2 = f"MM-H2[{short}{scale}]"
            tests[h1] = paired(df, arm, "keda_fair", "total_cost_usd")
            tests[h2] = paired(df, arm, "hpa_fair", "mean_excess", NI_MARGIN)
            meta[h1] = (const, scale, "cost vs `keda_fair`")
            meta[h2] = (const, scale, f"`mean_excess` NI vs `hpa_fair` ({NI_MARGIN})")
    holm = holm_bonferroni({k: v["p"] for k, v in tests.items()})

    w(f"\n## MM-H1 and MM-H2 (one Holm family of {len(tests)}, α = 0.05)\n")
    w("Registered together because they answer one question — does the "
      "controller survive being wrong? Each hypothesis PASSES **only if all "
      "six of its sub-tests pass**; any single failure fails it and names the "
      "constant that broke it.\n")
    w("\n| id | constant | belief | test | n | effect | d_z | Wilcoxon p | Holm alpha | paired-t p | verdict |")
    w("|---|---|---:|---|---:|---:|---:|---:|---:|---:|---|")
    for hid, r in tests.items():
        const, scale, what = meta[hid]
        hr = holm[hid]
        eff = (f"{r['rel'] * 100:+.1f}% cost" if hid.startswith("MM-H1")
               else f"{r['mean_diff']:+.4f} excess")
        w(f"| **{hid}** | `{const}` | {scale} | {what} | {r['n']} | {eff} | "
          f"{r['dz']:+.3f} | {r['p']:.3g} | {hr['threshold']:.5f} | "
          f"{r['t_p']:.3g} | {'PASS' if hr['reject'] else 'FAIL'} |")

    h1_sub = [k for k in tests if k.startswith("MM-H1")]
    h2_sub = [k for k in tests if k.startswith("MM-H2")]
    h1_pass = all(holm[k]["reject"] for k in h1_sub)
    h2_pass = all(holm[k]["reject"] for k in h2_sub)
    h1_broke = [meta[k][0] + f" @{meta[k][1]}" for k in h1_sub if not holm[k]["reject"]]
    h2_broke = [meta[k][0] + f" @{meta[k][1]}" for k in h2_sub if not holm[k]["reject"]]

    w(f"\n**MM-H1 {'PASS' if h1_pass else 'FAIL'}** — "
      + ("the cost win over `keda_fair` survives ±25% mismatch on every "
         "constant. The claim is mismatch-robust *within that band, one "
         "constant at a time*, and must be quoted with that scope.\n"
         if h1_pass else
         f"broken by: {', '.join(h1_broke)}. The cost claim depends on the "
         "controller knowing a constant it would not know in production. Per "
         "the prereg this is a **material limitation of the contribution**, "
         "reported here and carried into `RESULTS_MASTER.md`; no arm is "
         "retuned in response.\n"))
    w(f"**MM-H2 {'PASS' if h2_pass else 'FAIL'}** — "
      + ("SLO severity stays within the inherited 0.05 margin under ±25% "
         "mismatch on every constant.\n" if h2_pass else
         f"broken by: {', '.join(h2_broke)}. The SLO behaviour is "
         "belief-sensitive, which is the more serious of the two for an "
         "operator, and is reported as such.\n"))

    # --- MM-H3 (descriptive) ----------------------------------------------
    w("\n## MM-H3 — is degradation graceful? (descriptive, no test)\n")
    w("Mean `J` across the full ladder, with the step between neighbours. A "
      "cliff — a step far larger than its neighbours — is the finding if it "
      "appears, and the ladder exists to make one visible.\n")
    w("\n| constant | " + " | ".join(f"J @ {s}" for s in LADDER)
      + " | largest single step |")
    w("|---|" + "---:|" * (len(LADDER) + 1))
    cliffs = {}
    for const, short in CONSTANTS.items():
        js = []
        for scale in LADDER:
            sub = df[df.system == arm_for(short, scale)]
            js.append(float(sub.J.mean()) if not sub.empty else float("nan"))
        steps = [abs(js[i + 1] - js[i]) for i in range(len(js) - 1)]
        worst = max(steps)
        where = steps.index(worst)
        cliffs[const] = (worst, LADDER[where], LADDER[where + 1])
        w(f"| `{const}` | " + " | ".join(f"{v:.4g}" for v in js)
          + f" | **{worst:.4g}** ({LADDER[where]}→{LADDER[where + 1]}) |")
    w("\nThe steps are reported as measured; no cliff threshold was "
      "pre-registered, so none is invented here. The largest single step "
      "belongs to "
      + max(cliffs, key=lambda k: cliffs[k][0])
      + f", between {cliffs[max(cliffs, key=lambda k: cliffs[k][0])][1]} and "
      f"{cliffs[max(cliffs, key=lambda k: cliffs[k][0])][2]}.\n")

    # --- verdict -----------------------------------------------------------
    w("\n## Verdict\n")
    w(f"- **MM-H1** (cost win survives ±25% on every constant): "
      f"{'**PASS**' if h1_pass else '**FAIL**'}"
      + (f" — broken by {', '.join(h1_broke)}" if h1_broke else "") + ".")
    w(f"- **MM-H2** (severity non-inferiority survives ±25% on every "
      f"constant): {'**PASS**' if h2_pass else '**FAIL**'}"
      + (f" — broken by {', '.join(h2_broke)}" if h2_broke else "") + ".")
    w("\n**Scope, stated so it is not over-read.** This campaign perturbs one "
      "constant at a time over a ±25% band (with 0.5× and 2.0× on the ladder "
      "for shape). It does *not* test compound mismatch, structural "
      "mismatch — a plant of a different functional form — or a belief that "
      "drifts during a run. Those are separate experiments and are not "
      "claimed here.\n")

    out = record_path("RESULTS_MODEL_MISMATCH.md")
    out.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
