"""WP8b (B1, the three-knob live plane) -> RESULTS_WAVE4_LIVE_PLANE.md.

Pre-registration: `PREREG_WAVE4_LIVE_PLANE.md`.

THIS RECORD REPORTS A VOID EXPERIMENT, AND THAT IS THE PRE-REGISTERED OUTCOME.
The prereg's WL-H2 preflight gate exists to answer one question before any
three-knob comparison is scored: do the knobs actually move the substrate? On
this substrate they do not, so WL-H1 is void and the 4x4 matrix was NOT run to
completion. The prereg's instruction is explicit -- "If it raises: report
SUBSTRATE INADEQUATE; WL-H1 is void; do NOT fake or lower margins" -- and no
margin is touched here.

WHAT THIS RECORD IS BUILT FROM. There are no run metrics, because there are no
valid runs. It is built from the gate's own report, `knob_preflight.json`, and
from `tunnel_preflight.json`, which establishes that the free split-host route
was NOT the limiting factor.

A NOTE ON HOW THE VERDICT WAS REACHED, because it changed twice. The gate could
not run at all until three harness defects were fixed (EVAL_DIR NameError, a
UnicodeEncodeError printing its own output, and its report self-deleting with
the temp workdir). A fourth defect -- ordering the probe's tiers alphabetically
rather than by capability -- was manufacturing one of the three failure
criteria. The verdict below is from the run after all four were fixed. The
earlier readings are retained in `wp8b_substrate_evidence/` so the correction is
checkable rather than asserted.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from stats import record_path  # noqa: E402

REPO = Path(__file__).resolve().parents[2]
EV = REPO / "eval" / "results" / "wave4_live_plane_evidence"
SUB = REPO / "eval" / "results" / "wp8b_substrate_evidence"


def read(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def build() -> str:
    L: list[str] = []
    def w(s: str = "") -> None:
        L.append(s)

    knob = read(EV / "knob_preflight.json")
    tunnel = read(SUB / "tunnel_preflight.json")
    cache, tier = knob["cache"], knob["tier"]

    w("# B1 — the three-knob live plane: SUBSTRATE INADEQUATE, WL-H1 void (WP8b)")
    w()
    w("Generated by `analysis_wave4_live_plane.py` from evidence committed under "
      "`eval/results/wave4_live_plane_evidence/` and "
      "`eval/results/wp8b_substrate_evidence/`. Pre-registration: "
      "`PREREG_WAVE4_LIVE_PLANE.md`.")
    w()
    w()
    w("## Headline")
    w()
    w("**The WL-H2 knob-liveness gate returned SUBSTRATE INADEQUATE, so WL-H1 "
      "is void and the frozen 4 arms x 4 cells matrix was not run to "
      "completion.**")
    w()
    w("This is the pre-registered outcome, not a failure to explain away. "
      "`PREREG_WAVE4_LIVE_PLANE` states it: *\"If it raises: report SUBSTRATE "
      "INADEQUATE; WL-H1 is void; do NOT fake or lower margins.\"* **No margin "
      "was lowered.** The gate exists precisely so that a three-knob comparison "
      "is never scored on a substrate where the knobs do not move — which would "
      "produce arm differences that are noise wearing the shape of a result.")
    w()
    w()
    w("## The verdict")
    w()
    w(f"Gate report generated {knob['generated_at']} against tenant "
      f"`{knob['tenant']}`.")
    w()
    w("| knob | measurement | margin | live |")
    w("|---|---|---:|---|")
    w(f"| cache | hit **{cache['hit_rate_budgeted']:.2f}** @64 MB vs "
      f"**{cache['hit_rate_zero']:.2f}** @0 MB (delta "
      f"{cache['delta']:.2f}) | {cache['margin']} | "
      f"**{'yes' if cache['live'] else 'NO'}** |")
    w(f"| tier | `{tier['tier_a']}` {tier['mean_ms_a']:.1f} ms vs "
      f"`{tier['tier_b']}` {tier['mean_ms_b']:.1f} ms (delta "
      f"{tier['delta_ms']:.1f} ms) | "
      f"max({tier['abs_margin_ms']:.0f} ms, "
      f"{tier['rel_margin']:.0%}) | "
      f"**{'yes' if tier['live'] else 'NO'}** |")
    w()
    w("| tier sub-criterion | result |")
    w("|---|---|")
    w(f"| `routing_moved` | **{tier['routing_moved']}** |")
    w(f"| `latency_moved` | **{tier['latency_moved']}** |")
    w(f"| `ordering_correct` | {tier['ordering_correct']} |")
    w()
    w()
    w("## The root cause is one defect, not three")
    w()
    w("The decisive field is which tiers were actually observed serving under "
      "each pin:")
    w()
    w(f"- pinned to `{tier['tier_a']}` -> served "
      f"**{tier['tiers_seen_a']}**")
    w(f"- pinned to `{tier['tier_b']}` -> served "
      f"**{tier['tiers_seen_b']}**")
    w()
    w("**The tier pin is asymmetric.** Pinning the smaller tier routes "
      "exclusively to it; pinning the larger tier still serves a share of "
      "requests from the smaller one. That single leak accounts for both "
      "failing criteria: `routing_moved` is false by definition, and "
      "`latency_moved` is false *because of it* — the larger tier's mean "
      f"({tier['mean_ms_b']:.1f} ms) is dragged toward the smaller tier's "
      f"({tier['mean_ms_a']:.1f} ms), leaving {tier['delta_ms']:.1f} ms against "
      "the "
      f"{max(tier['abs_margin_ms'], tier['rel_margin'] * min(tier['mean_ms_a'], tier['mean_ms_b'])):.1f} ms "
      "the margin requires.")
    w()
    w(f"The cache knob is a separate and milder finding: it is **not inert but "
      f"under-powered**, moving the hit rate by {cache['delta']:.2f} against a "
      f"{cache['margin']} margin.")
    w()
    w()
    w("## The substrate was not the limitation")
    w()
    w("The free split-host route (`docs/WAVE4_FREE_ROUTE.md`) — a Kaggle P100 "
      "serving Qwen2.5-0.5B and Qwen2.5-3B behind a cloudflared quick tunnel — "
      "passed its own preflight before the gate ran:")
    w()
    w("| | |")
    w("|---|---:|")
    for k in tunnel.get("tiers", []):
        t = tunnel.get(k, {})
        w(f"| `{k}` mean ({t.get('model','?')}) | {t.get('mean_ms', 0):.1f} ms |")
    w(f"| tier gap | **{tunnel['delta_ms']:.1f} ms** vs "
      f"{tunnel['threshold_ms']:.1f} ms threshold |")
    w(f"| models echoed correctly | {tunnel['models_echoed']} |")
    w(f"| round-trip tolerance remaining | "
      f"{tunnel['extra_rtt_tolerance_ms']:.0f} ms |")
    w(f"| slowest tier vs premium SLO ({tunnel['ai_slo_premium_ms']:.0f} ms) | "
      f"{tunnel['slowest_tier_mean_ms']:.0f} ms — "
      f"{tunnel['slo_headroom_ms']:.0f} ms headroom |")
    w(f"| verdict | **{tunnel['verdict']}** |")
    w()
    w("So the tunnel carried a material tier gap and the models answered "
      "correctly. **The knobs, not the route, are what failed.** A rented GPU "
      "in the same host would not change this verdict.")
    w()
    w()
    w("## Four harness defects, all found by running this path for the "
      "first time")
    w()
    w("`POLYFORGE_EVAL_LIVE_AI=1` had never been set on a real run — WP8b was "
      "gated on a GPU the project did not have, and WP8a deliberately runs with "
      "it unset. So this code had never executed:")
    w()
    w("| defect | effect |")
    w("|---|---|")
    w("| `NameError: EVAL_DIR` in `run_knob_preflight` | the gate could not "
      "launch; all 16 runs failed identically |")
    w("| `UnicodeEncodeError` printing the gate's own output | the gate "
      "crashed reporting its verdict, through cp1252 |")
    w("| `knob_preflight.json` written into a `TemporaryDirectory` | the "
      "verdict's machine-readable evidence self-deleted — the same loss that "
      "took attempt 2's k6 summary |")
    w("| tiers ordered **alphabetically** rather than by capability | "
      "`sorted([\"small\",\"mid\"])` = `[\"mid\",\"small\"]`, inverting the "
      "probe's ascending-capability convention and **manufacturing** an "
      "`ordering_correct: false` |")
    w()
    w("The fourth is the one that matters for reading this record: it was "
      "producing a failure criterion that was an artefact of the harness. With "
      "it fixed, `ordering_correct` is **true** and the verdict rests only on "
      "the genuine routing leak. The pre-fix readings are retained in "
      "`wp8b_substrate_evidence/` so the correction can be checked rather than "
      "taken on trust.")
    w()
    w()
    w("## What this does and does not license")
    w()
    w("**Does not:** any WL-H1 claim. There are no valid runs — the harness "
      "reported `valid_runs: 0` — and no arm comparison, cost figure or "
      "fairness number from this experiment exists or may be quoted.")
    w()
    w("**Does:** the finding that the tier knob does not pin exclusively on "
      "this build. That is a defect in the system under test, surfaced by a "
      "pre-registered gate doing exactly its job, and it is worth more than a "
      "scored matrix built on knobs that do not move.")
    w()
    w("Per the roadmap's risk register — *\"WP8: WL-H2 inert knob | SUBSTRATE "
      "INADEQUATE, WL-H1 void, report honestly, fix substrate, re-sit\"* — the "
      "next step is a gateway fix for the asymmetric pin, then a re-sit under a "
      "new pre-registration. Neither is done here, and this record does not "
      "anticipate their outcome.")
    w()
    return "\n".join(L) + "\n"


def main() -> int:
    out = record_path("RESULTS_WAVE4_LIVE_PLANE.md")
    out.write_text(build(), encoding="utf-8")
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
