#!/usr/bin/env python3
"""PREREG_LIVE_SOAK.md -> RESULTS_LIVE_SOAK.md (WP14, attempt 2).

**This record reports a FAILED sitting.** The soak ran its full 24 hours and
was then rejected by the harness's own post-hoc validity gate,
`cluster_backend.check_k6_delivery`, which found that 36.4% of the load
generator's requests never succeeded. Zero metrics rows were recorded, so
the run is unscoreable rather than merely weak.

It is written up because `PREREG_LIVE_SOAK.md` §Outcome handling says so:
*"Any hypothesis FAILS — that is the finding and it is the headline of the
record."* A failed sitting that is quietly re-run instead of recorded is how
"run until it passes" starts.

Every number below is parsed at run time from evidence committed under
`eval/results/wp14_attempt2/` — the four injector logs, the runner's verdict,
and the run record extracted from the (gitignored, Zenodo-archived) DuckDB
before it could be lost. Nothing is transcribed by hand, so this record
rebuilds on a clean clone like every other.

    python analysis_live_soak.py
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from stats import record_path  # noqa: E402

_RESULTS = Path(__file__).resolve().parents[2] / "eval" / "results"
EVIDENCE = _RESULTS / "wp14_attempt2"

# Frozen by PREREG_LIVE_SOAK.md §Design. The soak targets 24 h with a 12 h
# minimum; faults alternate crash/throttle on a 3 h spacing from T0.
TARGET_S = 86_400
MINIMUM_S = 43_200
FAULT_OFFSETS = [7200, 18000, 28800, 39600, 50400, 61200, 72000, 82800]
# SK-H3's threshold, read off the committed B2 row rather than invented
# (eval/results/live_chaos_p99_runs.csv, phase7_chaos_p99 / crud_bursty).
B2_CRUD_P99_MS = 8.0072

FAULT_RE = re.compile(
    r"=== FAULT (?P<n>\d) (?P<kind>[a-z-]+) at (?P<ts>[\d:]+) \(T\+(?P<off>\d+)s\)")


def load_injector_events() -> list[dict]:
    """Every injected fault, parsed from the four committed injector logs.

    The injectors timestamp in UTC while the run is discussed in local time
    (UTC+6); the T+offset is the unambiguous key and is what this sorts on.
    """
    events: dict[int, dict] = {}
    for log in sorted(EVIDENCE.glob("wp14_inject_*.log")):
        text = log.read_text(encoding="utf-8", errors="replace")
        for m in FAULT_RE.finditer(text):
            off = int(m.group("off"))
            events[off] = {
                "offset_s": off,
                "kind": m.group("kind"),
                "utc": m.group("ts"),
                "log": log.name,
            }
        # Recovery-side markers: which planner pod was destroyed, and whether
        # the throttle was both applied and removed.
        for pod in re.findall(r'pod "([^"]+)" deleted', text):
            for e in events.values():
                if e["log"] == log.name and e["kind"] == "planner-crash" and "pod" not in e:
                    e["pod"] = pod
                    break
        for cleared in re.findall(r"throttle cleared at ([\d:]+)", text):
            for e in events.values():
                if e["log"] == log.name and e["kind"] == "apiserver-throttle" \
                        and "cleared" not in e:
                    e["cleared"] = cleared
                    break
    return [events[o] for o in sorted(events)]


def load_run_record() -> dict:
    return json.loads((EVIDENCE / "run_record.json").read_text(encoding="utf-8"))


def load_runner_verdict() -> dict:
    """The runner's own JSON report, as printed at the end of the run."""
    text = (EVIDENCE / "runner_attempt2.log").read_text(encoding="utf-8",
                                                        errors="replace")
    start = text.index("{")
    return json.loads(text[start:text.index("}", start) + 1])


def fail_rate_from_error(error: str) -> str | None:
    m = re.search(r"k6 reported ([\d.]+%) failed requests", error or "")
    return m.group(1) if m else None


def elapsed_from_runner() -> int | None:
    text = (EVIDENCE / "runner_attempt2.log").read_text(encoding="utf-8",
                                                        errors="replace")
    m = re.search(r"\((\d+)s elapsed\)", text)
    return int(m.group(1)) if m else None


def main() -> None:
    events = load_injector_events()
    record = load_run_record()
    verdict = load_runner_verdict()
    elapsed = elapsed_from_runner()
    fail_rate = fail_rate_from_error(record.get("error", ""))

    L: list[str] = []
    w = L.append

    w("# Live CRUD-plane soak — attempt 2: the run is INVALID (WP14)\n")
    w("Generated by `analysis_live_soak.py` from the evidence committed under "
      "`eval/results/wp14_attempt2/`. Pre-registration: "
      "`PREREG_LIVE_SOAK.md`, committed and pushed before the run.\n")

    # --- headline ---------------------------------------------------------
    w("\n## Headline — SK-H4 FAILS, and the run is unscoreable\n")
    w(f"The soak ran for **{elapsed:,} s** "
      f"({elapsed / 3600:.1f} h) against a {TARGET_S // 3600} h target, "
      "injected all eight of its frozen faults, and was then **rejected by "
      "the harness's own validity gate**:\n")
    w("\n```")
    w(f"k6 reported {fail_rate} failed requests (>1%): the load did not land, "
      "so the low")
    w("cost/violation this run would record are artifacts of traffic that "
      "never arrived")
    w("```\n")
    w(f"`cluster_backend.check_k6_delivery` exists precisely to catch this. "
      "Its own docstring states the failure mode it guards: *\"k6 exits 0 "
      "even when every request failed … an expired token, a dead "
      "port-forward or a 429 storm all produced a complete-looking result "
      "with an artificially low cost and violation.\"* The gate did its "
      "job.\n")
    w(f"**Metrics rows recorded: {record['metrics_rows']}.** The run produced "
      "no `crud_p95`, no `mean_violation`, no cost. It is not a weak result; "
      "it is an absent one.\n")
    w("\n| runner verdict | value |")
    w("|---|---:|")
    for key in ("expected_runs", "valid_runs", "failed_runs", "null_metrics"):
        w(f"| `{key}` | {verdict[key]} |")
    w(f"| `ok` | **{str(verdict['ok']).lower()}** |")

    # --- hypotheses -------------------------------------------------------
    w("\n## Hypotheses\n")
    w("\n| id | claim | verdict |")
    w("|---|---|---|")
    w("| **SK-H4** | zero invalid-run signatures across the soak | "
      f"**FAIL** — `check_k6_delivery` rejected the run at {fail_rate} "
      "failed requests |")
    w("| **SK-H3** | hour-bucketed `crud_p95` ≤ the committed B2 p99 of "
      f"{B2_CRUD_P99_MS} ms | **UNSCOREABLE** — no metrics exist |")
    w("| **SK-H2** | audit-record continuity across every degraded cycle | "
      "**UNSCOREABLE** — no metrics exist |")
    w("| **SK-H1** | every injected fault recovers without operator "
      "intervention | **UNSCOREABLE as frozen** — see below |")

    w("\n### SK-H1 — why it is not scored, despite the observations\n")
    w("SK-H1 was frozen as a metric-based test: recovery is judged by "
      "post-fault `mean_violation` returning within `CHAOS_TOL = 0.05` of "
      "the pre-fault level. **That test cannot run — there are no "
      "violations recorded to compare.**\n")
    w("What does exist is *operational* evidence, gathered live against the "
      "cluster at each occurrence and preserved in "
      "`eval/results/wp14_attempt2/FAULT_JOURNAL.md`: pod ages, restart "
      "counts, `Policy` conditions and throughput checked at the moment of "
      "each fault. It records **7 of 8 injections showing observed "
      "perturbation followed by recovery without intervention**, and the "
      "eighth (the final throttle) as injected with *no observed "
      "perturbation at all* — not padded into an eighth recovery.\n")
    w("**That evidence is reported here as an observation, not as a passed "
      "hypothesis.** It was collected by an observer watching a run that "
      "turns out to have been invalid, and it is qualitative where the "
      "prereg demanded quantitative. Quoting it as \"SK-H1 passed, 7/8\" "
      "would be exactly the laundering this record exists to prevent.\n")

    # --- what did happen --------------------------------------------------
    w("\n## The fault schedule did execute\n")
    w("Parsed from the committed injector logs. Timestamps are **UTC** (the "
      "injector's own clock); local time is UTC+6.\n")
    w("\n| # | T+ | fault | UTC | injector evidence |")
    w("|---:|---:|---|---|---|")
    for i, e in enumerate(events, 1):
        detail = (f"killed `{e['pod'].split('/')[-1]}`" if "pod" in e
                  else f"applied, cleared {e.get('cleared', '?')}")
        w(f"| {i} | {e['offset_s'] / 3600:.0f} h | `{e['kind']}` | "
          f"{e['utc']} | {detail} |")
    delivered = [e["offset_s"] for e in events]
    w(f"\nAll **{len(events)}/{len(FAULT_OFFSETS)}** frozen offsets fired"
      + (" exactly as scheduled.\n" if delivered == FAULT_OFFSETS else
         f" — scheduled {FAULT_OFFSETS}, observed {delivered}.\n"))
    w("So the *fault-injection mechanism* worked. The defect is in the load "
      "delivery path, not the chaos path — which matters, because it means "
      "attempt 3 does not need the injectors redesigned.\n")

    # --- root cause -------------------------------------------------------
    w("\n## Root-cause lead (not confirmed)\n")
    w("Two of the sixteen `control-plane` pods show exactly one restart "
      "each, timed at roughly one minute after T0. `kubectl port-forward "
      "service/…` resolves to **one specific pod** when it starts and does "
      "not follow the Service if that pod is replaced; the harness spawns it "
      "once (`cluster_backend.execute`, `subprocess.Popen`, output to "
      "`DEVNULL`) and never health-checks or restarts it for the life of a "
      "run. If the forward pinned to one of those two pods, that is a real "
      "mechanism for sustained delivery failure.\n")
    w(f"**It does not cleanly explain {fail_rate} on its own** — a single "
      "dead pinned pod for 24 h would read closer to 100% than to a third. "
      "So this is a lead, not a diagnosis, and it is recorded as one.\n")
    w("**The evidence that would settle it was destroyed by the harness.** "
      "`k6-summary.json` — which carries the failure *timeline*, and would "
      "show whether the failures began at minute one or accumulated late — "
      "was written into a `tempfile.TemporaryDirectory` and deleted when the "
      "run exited. Fixing that is step 1 of attempt 3, and it is the reason "
      "this record cannot say more.\n")

    # --- disposition ------------------------------------------------------
    w("\n## Disposition\n")
    w("Per `PREREG_LIVE_SOAK.md` §Outcome handling, which fixed this "
      "response before the run:\n")
    w("- The failure **is** the finding and is the headline of this record.")
    w("- The record is **not truncated or spliced**. The run is reported at "
      "the length it reached, with the reason it was rejected.")
    w("- A re-sit happens under a **NEW pre-registration with one changed "
      "factor** (`PREREG_LIVE_SOAK_V2.md`, delivery-path resilience), "
      "committed and pushed before it runs — mirroring the RB-H1 follow-up "
      "pattern. This is the prereg's contingency clause being exercised as "
      "designed, not a departure from it.")
    w("- **24 h remains the target.** It is the reason this work package "
      "exists for a Transactions-tier pitch; shrinking it after two failed "
      "sittings would be optimising for finishing rather than for the "
      "argument.\n")
    w("Attempt 1, for the record, was voided earlier at 2 h 45 m: "
      "`chaos_inject.sh` detected the load window with `pgrep -x k6`, which "
      "cannot see a native `k6.exe` under Git Bash on Windows, so all four "
      "injectors timed out and aborted while k6 ran the whole time. Fixed "
      "with a `tasklist` fallback, verified against the live process before "
      "attempt 2 relaunched.\n")

    out = record_path("RESULTS_LIVE_SOAK.md")
    out.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"wrote {out}")
    print(f"faults parsed: {len(events)}/8 | fail rate: {fail_rate} | "
          f"metrics rows: {record['metrics_rows']}")


if __name__ == "__main__":
    main()
