"""PREREG_STRUCTURAL_MISMATCH.md -> RESULTS_STRUCTURAL_MISMATCH.md: do the
FJ wins survive a planner that is wrong about the plant's FORM?

FROZEN with the pre-registration; not edited after the run. The test is the
one PREREG_FAIR_J froze, imported from its (equally frozen) scorer, so the
two campaigns are judged by identical code.

    python analysis_structural_mismatch.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
from analysis_fair_j import (  # noqa: E402
    BOOT_N, BOOT_SEED, DESIGN, NI_MARGIN, complete_design_points, design_diffs,
    noninferior, superiority,
)
from stats import composite_objective, holm_bonferroni, record_path  # noqa: E402

RESULTS = HERE.parents[1] / "eval" / "results"
RECORD = "RESULTS_STRUCTURAL_MISMATCH.md"
ALPHA = 0.05
BLIND = "jcac_converged_blind"
CALIBRATED = "jcac_calibrated_blind"
ORACLE = "jcac_converged"
COMPARATORS = {"H1": "keda_fair", "H2": "jcac_nojoint_v2_tuned"}
ALSO = "hpa_fair"
ARMS = [BLIND, CALIBRATED, ORACLE, *COMPARATORS.values(), ALSO]
PLANTS = [("latency", "measured latency model"), ("mixture", "mixture p95"),
          ("tierwu", "measured tier work units"), ("live", "live-fitted B1' plant"),
          ("combined", "latency + mixture + tier work units")]
COLUMNS = ["system", "workload", "tenant_mix", "cluster_size", "rep", "total_cost_usd",
           "mean_violation", "mean_jain", "mean_excess", "tier_none_step_share"]


def load(plant: str) -> pd.DataFrame:
    db = RESULTS / f"raw_sim_matrix_sm_{plant}.duckdb"
    if db.exists():
        import duckdb

        con = duckdb.connect(str(db), read_only=True)
        try:
            return con.execute(
                "select r.system, r.workload, r.tenant_mix, r.cluster_size, r.rep, "
                "m.total_cost_usd, m.mean_violation, m.mean_jain, m.mean_excess, "
                "m.tier_none_step_share from runs r join metrics m on r.run_id = m.run_id "
                "where r.status = 'valid'").fetchdf()
        finally:
            con.close()
    return pd.read_csv(RESULTS / f"metrics_matrix_sm_{plant}.csv.gz",
                       float_precision="round_trip")[COLUMNS]


def prepare(df: pd.DataFrame) -> pd.DataFrame:
    df = complete_design_points(df, ARMS)
    return df.assign(J=composite_objective(df))


def score(frames: dict[str, pd.DataFrame], treatment: str = BLIND, prefix: str = "SM-H") -> dict[str, dict]:
    """One Holm family over every plant x comparator: SM-H1/H2 for the blind
    planner (confirmatory), SM-S1/S2 for the calibrated blind one (secondary)."""
    res = {}
    for plant, _ in PLANTS:
        for tag, comp in COMPARATORS.items():
            r = superiority(design_diffs(frames[plant], treatment, comp, "J"))
            res[f"{prefix}{tag[1:]}[{plant}]"] = {**r, "plant": plant, "vs": comp}
    holm = holm_bonferroni({hid: r["p"] for hid, r in res.items()}, ALPHA)
    for hid, r in res.items():
        r["threshold"] = holm[hid]["threshold"]
        r["pass"] = bool(holm[hid]["reject"] and r["ci"][1] < 0)
    return res


def build(frames: dict[str, pd.DataFrame]) -> str:
    frames = {p: prepare(df) for p, df in frames.items()}
    res = score(frames)
    L = ["# Structural model mismatch: do the FJ wins survive a planner wrong about the plant's form?", "",
         "Generated by `analysis_structural_mismatch.py`, frozen with `PREREG_STRUCTURAL_MISMATCH.md`. In "
         f"each plant, `{BLIND}` plans with the PUBLISHED model forms while the plant runs the altered form; "
         f"`{ORACLE}` sees the plant. Unit: the design point. A PASS needs the one-sided Wilcoxon p at or "
         f"below its Holm threshold (one family of {len(res)}) AND the 95% bootstrap CI of the mean J "
         f"difference entirely below 0 ({BOOT_N:,} resamples, seed {BOOT_SEED}). Negative = the blind "
         "planner is better.", "",
         "## Confirmatory", "",
         "| id | plant | vs | design points | ΔJ | d_z | 95% CI of ΔJ | blind better in | Wilcoxon p | "
         "Holm threshold | verdict |", "|---|---|---|---:|---:|---:|---|---:|---:|---:|---|"]
    for hid, r in res.items():
        L.append(f"| **{hid}** | {r['plant']} | `{r['vs']}` | {r['n']} | {r['mean']:+.4f} | {r['dz']:+.2f} | "
                 f"[{r['ci'][0]:+.4f}, {r['ci'][1]:+.4f}] | {r['better']:.0%} | {r['p']:.3g} | "
                 f"{r['threshold']:.4f} | {'PASS' if r['pass'] else 'FAIL'} |")
    sec = score(frames, CALIBRATED, "SM-S")
    L += ["", f"## Secondary: `{CALIBRATED}` (the blind planner plus the B1' online calibration; own Holm "
          f"family of {len(sec)}; not confirmatory)", "",
          "| id | plant | vs | design points | ΔJ | d_z | 95% CI of ΔJ | better in | Wilcoxon p | "
          "Holm threshold | verdict |", "|---|---|---|---:|---:|---:|---|---:|---:|---:|---|"]
    for hid, r in sec.items():
        L.append(f"| **{hid}** | {r['plant']} | `{r['vs']}` | {r['n']} | {r['mean']:+.4f} | {r['dz']:+.2f} | "
                 f"[{r['ci'][0]:+.4f}, {r['ci'][1]:+.4f}] | {r['better']:.0%} | {r['p']:.3g} | "
                 f"{r['threshold']:.4f} | {'PASS' if r['pass'] else 'FAIL'} |")
    L += ["", f"## SLO guard: `mean_excess` non-inferiority (one-sided 95% bootstrap bound < {NI_MARGIN})", "",
          "| plant | vs | mean diff | 95% upper bound | verdict |", "|---|---|---:|---:|---|"]
    for plant, _ in PLANTS:
        for comp in COMPARATORS.values():
            g = noninferior(design_diffs(frames[plant], BLIND, comp, "mean_excess"))
            L.append(f"| {plant} | `{comp}` | {g['mean']:+.4f} | {g['ucb']:+.4f} | "
                     f"{'PASS' if g['ni'] else 'FAIL'} |")
    L += ["", "## The price of believing the wrong form (descriptive)", "",
          f"J of the blind planner minus J of the oracle (`{ORACLE}`), per design point; positive = the "
          f"wrong belief costs. Beside it, the blind planner against `{ALSO}`.", "",
          "| plant | blind − oracle ΔJ | 95% CI | blind vs hpa_fair ΔJ | 95% CI | AI shed, blind |",
          "|---|---:|---|---:|---|---:|"]
    for plant, label in PLANTS:
        df = frames[plant]
        cost = superiority(design_diffs(df, BLIND, ORACLE, "J"))
        hpa = superiority(design_diffs(df, BLIND, ALSO, "J"))
        shed = df[df.system == BLIND].tier_none_step_share.mean()
        L.append(f"| {plant} ({label}) | {cost['mean']:+.4f} | [{cost['ci'][0]:+.4f}, {cost['ci'][1]:+.4f}] | "
                 f"{hpa['mean']:+.4f} | [{hpa['ci'][0]:+.4f}, {hpa['ci'][1]:+.4f}] | {shed:.1%} |")
    L += ["", "## Per-arm means per plant", "", "| plant | arm | J | cost $ | mean_violation | mean_excess |",
          "|---|---|---:|---:|---:|---:|"]
    for plant, _ in PLANTS:
        df = frames[plant]
        for arm in ARMS:
            s = df[df.system == arm]
            L.append(f"| {plant} | `{arm}` | {s.J.mean():.4f} | {s.total_cost_usd.mean():.4f} | "
                     f"{s.mean_violation.mean():.4f} | {s.mean_excess.mean():.4f} |")
    L.append("")
    return "\n".join(L) + "\n"


def main() -> int:
    out = record_path(RECORD)
    out.write_text(build({p: load(p) for p, _ in PLANTS}), encoding="utf-8")
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
