"""Can SK-H1's rule tell a fault from a quiet minute? (W2, descriptive)

`RESULTS_LIVE_SOAK_V8.md` scores SK-H1 as **FAIL on 1 of 8 injections** and says
the evidence bearing on interpretation is that `crud_p95` oscillates on a
roughly four-minute cycle present before, during and after the fault, so a rule
comparing a recovery MAXIMUM against a pre-window MEDIAN is scored
peak-against-trough whenever a burst lands in the window.

That is stated as an observation. This measures it.

**Method: the same statistic, where nothing happened.** SK-H1's rule is copied
from `analysis_live_soak_v8.score_skh1` rather than re-derived — median of the
600 s before, maximum of the 300 s after a 'recovery' offset, FAIL above a 20%
band — and applied at every minute of the run whose windows do not overlap any
injected fault. If the rule fires about as often on quiet minutes as on faults,
its one FAIL carries no information about recovery; if it almost never fires on
quiet minutes, the FAIL is about the fault after all.

**This changes nothing.** `RESULTS_LIVE_SOAK_V8.md` stands exactly as committed,
SK-H1 stays FAILED, and no threshold here is applied to that record. Descriptive
and desk-only, the same standing as `RESULTS_WINDOW_CHARACTER.md` (M3): it
explains a published failure rather than revising it.

    python analysis_skh1_discriminability.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from analysis_live_soak_v8 import (EV, SKH1_BAND, bucket_epoch,  # noqa: E402
                                   timeline_faults)
from stats import record_path  # noqa: E402

RECORD = "RESULTS_SKH1_DISCRIMINABILITY.md"
PRE_S = 600           # SK-H1's baseline window
REC_S = 300           # SK-H1's recovery window
GUARD_S = 900         # keep a null window clear of any real fault by this much


def fine_buckets() -> list[dict]:
    data = json.loads((EV / "eval-export-fine.json").read_text(encoding="utf-8"))
    return sorted(data["buckets"], key=bucket_epoch)


def deviation(fine: list[dict], pre_start: int, rec_start: int) -> float | None:
    """SK-H1's statistic, verbatim: median of the pre-window against the MAXIMUM
    of the recovery window, as a fraction of the median."""
    pre = [b["crud_p95_ms"] for b in fine
           if pre_start <= bucket_epoch(b) < pre_start + PRE_S]
    rec = [b["crud_p95_ms"] for b in fine
           if rec_start < bucket_epoch(b) <= rec_start + REC_S]
    if not pre or not rec:
        return None
    base = sorted(pre)[len(pre) // 2]
    return (max(rec) - base) / base if base else None


def null_windows(fine: list[dict], faults) -> list[float]:
    """Every minute whose SK-H1 windows are clear of every injected fault."""
    blocked = [(s - GUARD_S, e + GUARD_S) for _, s, e in faults]
    lo, hi = bucket_epoch(fine[0]), bucket_epoch(fine[-1])
    out = []
    for t in range(lo + PRE_S, hi - REC_S, 60):
        span = (t - PRE_S, t + REC_S)
        if any(span[0] < b_hi and b_lo < span[1] for b_lo, b_hi in blocked):
            continue
        dev = deviation(fine, t - PRE_S, t)
        if dev is not None:
            out.append(dev)
    return out


def main() -> int:
    fine = fine_buckets()
    faults = timeline_faults()
    devs = null_windows(fine, faults)
    if not devs:
        raise SystemExit("no fault-free windows: nothing to compare against")

    fired = [d for d in devs if d > SKH1_BAND]
    rate = len(fired) / len(devs)
    ordered = sorted(devs)

    def pct(p: float) -> float:
        return ordered[min(int(p * len(ordered)), len(ordered) - 1)]

    L: list[str] = []
    w = L.append
    w("# Can SK-H1's rule tell a fault from a quiet minute? (W2)\n")
    w("Generated by `analysis_skh1_discriminability.py`. **Descriptive, no "
      "pre-registration, and it revises nothing.** `RESULTS_LIVE_SOAK_V8.md` "
      "stands exactly as committed and SK-H1 stays **FAILED**; this measures a "
      "claim that record makes in prose about *why* it failed.\n")

    w("\n## The question\n")
    w("V8 reports SK-H1 FAIL on 1 of 8 injections, and observes that "
      "`crud_p95` oscillates on a roughly four-minute cycle present before, "
      "during and after the failing fault — so the frozen rule, which compares "
      "a recovery **maximum** against a pre-window **median**, is scored "
      "peak-against-trough whenever a burst lands in the window. If that is "
      "right, the rule should fire at a similar rate on windows where **no "
      "fault occurred at all**.\n")

    w("\n## Method\n")
    w("SK-H1's statistic is imported from `analysis_live_soak_v8`, not "
      "re-implemented: median of the 600 s baseline against the maximum of the "
      "300 s recovery window, against the frozen 20% band. It is applied at "
      f"every minute whose windows clear every injected fault by {GUARD_S} s.\n")

    w("\nThe comparison is like for like, and that is checked rather than "
      "assumed: `test_skh1_discriminability.py` asserts that this module's "
      "`deviation()` reproduces V8's own score **exactly** for all eight "
      "injections. Importing the function is not the same as applying it "
      "identically — the window offsets could still differ — so the property "
      "the argument rests on is pinned by a test.\n")

    w("\n| | |")
    w("|---|---:|")
    w(f"| fault-free windows tested | {len(devs)} |")
    w(f"| of those, deviation > {SKH1_BAND:.0%} | **{len(fired)}** |")
    w(f"| **false-positive rate** | **{rate:.1%}** |")
    w(f"| injected faults scored by V8 | 8 |")
    w(f"| of those, FAILED | 1 (12.5%) |")

    w("\n## Distribution of the deviation on quiet windows\n")
    w("| quantile | deviation |")
    w("|---|---:|")
    for p, label in ((0.5, "median"), (0.75, "p75"), (0.9, "p90"),
                     (0.95, "p95"), (0.99, "p99")):
        w(f"| {label} | {pct(p):+.1%} |")
    w(f"| max | {max(devs):+.1%} |")

    # Where the one observed failure sits among windows where nothing happened.
    observed_dev = 0.754      # V8's failing injection, 2026-08-29T16:09:52Z
    below = sum(1 for d in devs if d < observed_dev) / len(devs)

    w("\n## Where the one real failure sits in that distribution\n")
    w(f"V8's failing injection deviated **+75.4%**. Among the {len(devs)} "
      f"fault-free windows, **{below:.1%}** deviate less than that — so the "
      f"failure sits at about the **{below * 100:.0f}th percentile of minutes "
      f"in which no fault was injected at all**. It is not an outlier against "
      f"the run's own background; it is an ordinary excursion of this metric.\n")

    w("\n## Reading\n")
    expected = rate * 8
    if rate >= 0.05:
        w(f"**The rule is not discriminative on this metric.** On windows where "
          f"nothing was injected it exceeds its own band **{rate:.1%}** of the "
          f"time, which over 8 injections predicts **{expected:.1f}** failures "
          f"from the oscillation alone. V8 observed **1**. A rule that fires "
          f"this readily on quiet minutes cannot distinguish a controller that "
          f"recovered badly from one that was sampled at the wrong phase, so "
          f"SK-H1's single FAIL is evidence about the rule and the metric — not "
          f"about recovery.\n")
    else:
        w(f"**The rule does discriminate.** On fault-free windows it exceeds its "
          f"band only **{rate:.1%}** of the time, predicting **{expected:.2f}** "
          f"failures across 8 injections against the 1 observed. The oscillation "
          f"explanation in V8 does not account for the failure on this evidence, "
          f"and the FAIL should be read as being about the fault.\n")

    w("**What this does not do.** It does not re-score SK-H1, relax its band, "
      "or touch `RESULTS_LIVE_SOAK_V8.md`. Changing a frozen rule after seeing "
      "its result is what these pre-registrations exist to prevent; measuring "
      "what the rule can and cannot resolve is a different act, and it belongs "
      "in the limitations rather than in the verdict. The metric itself carries "
      "the caveat V5 froze: `crud_p95` is CPU service time, not service "
      "latency.\n")

    record_path(RECORD).write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"wrote {record_path(RECORD)}")
    print(f"null windows {len(devs)} | fired {len(fired)} | rate {rate:.1%} | "
          f"expected-over-8 {expected:.2f} | observed 1")
    return 0


if __name__ == "__main__":
    sys.exit(main())
