"""W7 — did the load actually spread across nodes? (PREREG_MULTINODE.md)

Written BEFORE the sitting's numbers existed, and pushed with the
pre-registration, so the verdicts below are decided by the rules in the prereg
rather than described after reading the evidence.

The measurement this reads did not exist until session 43.
`LoadDistributionSampler` reads `kubectl top pods`, which carries a pod name
and a CPU figure and nothing else, so every live record in this repository
reports per-POD spread and none of them says which NODE served anything. That
is what actually blocked W7 — not the GPU the roadmap named, since the CRUD
path uses none and the 24 h soak drove 298 rps with no model in the loop.

Hypotheses, frozen:

  MN-H1 (claim)   >= 2 distinct nodes in node_shares AND busiest share < 0.90.
                  The threshold is loose on purpose: packing is the
                  scheduler's business, PINNING is the failure to catch.
  MN-H2 (gating)  every pod in cpu_ms resolved to a node (no "unknown"), and
                  >= 10 samples. On failure MN-H1 is VOID, not FAILED - a
                  spread claim built on partial attribution is exactly the
                  vacuous instrument WP14 hit three times.
  MN-H3 (descr.)  if the deployment held one replica throughout, MN-H1 is
                  VACUOUS: one pod can only be on one node, which is a fact
                  about the demand and not about the cluster.

    python analysis_multinode.py [--evidence DIR]
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from stats import record_path  # noqa: E402

RECORD = "RESULTS_MULTINODE.md"
DEFAULT_EVIDENCE = (Path(__file__).resolve().parents[2] / "eval" / "results"
                    / "multinode_crud_evidence")
MIN_SAMPLES = 10
MAX_BUSIEST_SHARE = 0.90
MIN_NODES = 2


def load_distribution(evidence: Path) -> dict:
    path = evidence / "load_distribution.json"
    if not path.exists():
        raise SystemExit(
            f"no load_distribution.json under {evidence}. The sitting either "
            f"did not run or did not reach the load window; that is a VOID "
            f"sitting under the prereg's stopping rule, not a FAIL.")
    return json.loads(path.read_text(encoding="utf-8"))


def verdicts(dist: dict) -> dict:
    cpu_ms = dist.get("cpu_ms", {})
    node_shares = dist.get("node_shares", {})
    samples = int(dist.get("samples", 0))

    unattributed = "unknown" in node_shares
    h2 = (not unattributed) and samples >= MIN_SAMPLES and bool(cpu_ms)

    busiest = max(node_shares.values()) if node_shares else 1.0
    nodes = len([n for n in node_shares if n != "unknown"])
    single_pod = len(cpu_ms) <= 1

    if not h2:
        h1 = "VOID"
    elif single_pod:
        h1 = "VACUOUS"
    elif nodes >= MIN_NODES and busiest < MAX_BUSIEST_SHARE:
        h1 = "PASS"
    else:
        h1 = "FAIL"
    return {"h1": h1, "h2": "PASS" if h2 else "FAIL", "samples": samples,
            "nodes": nodes, "busiest": busiest, "pods": len(cpu_ms),
            "unattributed": unattributed, "node_shares": node_shares,
            "failures": int(dist.get("failures", 0))}


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--evidence", default=str(DEFAULT_EVIDENCE))
    args = ap.parse_args()

    dist = load_distribution(Path(args.evidence))
    v = verdicts(dist)

    L: list[str] = []
    w = L.append
    w("# Did the load actually spread across nodes? (W7)\n")
    w("Generated by `analysis_multinode.py`. Pre-registration: "
      "`PREREG_MULTINODE.md`, committed and pushed before the campaign ran.\n")
    w("\n**The measurement is newer than the question.** Every live record "
      "before this one reports per-pod spread, because `kubectl top pods` — "
      "the sampler's only input until session 43 — carries a pod name and a "
      "CPU figure and nothing else. No sitting at any demand could have "
      "produced node-level evidence, which is what actually blocked W7 rather "
      "than the GPU the roadmap named.\n")

    w("\n## What ran\n")
    w("| | |")
    w("|---|---|")
    w("| experiment | `eval/experiments/multinode_crud.yaml` |")
    w("| cluster | kind, `medium` — 4 nodes |")
    w("| workload | `crud_bursty` (CRUD only: no GPU, no tier backend) |")
    w("| system | `jcac` |")
    w(f"| samples | {v['samples']} (failures {v['failures']}) |")
    w(f"| pods observed | {v['pods']} |")
    w(f"| nodes observed | {v['nodes']} |")

    w("\n## Where the CPU went\n")
    w("| node | share of observed CPU |")
    w("|---|---:|")
    for node, share in sorted(v["node_shares"].items(),
                              key=lambda kv: (-kv[1], kv[0])):
        w(f"| `{node}` | {share:.4f} |")

    w("\n## Verdicts\n")
    w(f"**MN-H2 {v['h2']}** (gating) — every observed pod resolved to a node "
      f"{'and' if v['h2'] else 'or'} the sampler took at least {MIN_SAMPLES} "
      f"samples. Unattributed pods present: "
      f"{'yes' if v['unattributed'] else 'no'}.\n")

    if v["h1"] == "VOID":
        w("\n**MN-H1 VOID** — the gate failed, so the spread claim is not "
          "evaluated. Per the prereg this is a VOID rather than a FAIL: a "
          "claim about node spread built on partial attribution is the "
          "vacuous-instrument failure this project has already hit three "
          "times, and reporting it as a controller result would repeat that.\n")
    elif v["h1"] == "VACUOUS":
        w(f"\n**MN-H1 VACUOUS** — {v['pods']} pod(s) were observed. One pod "
          "can only be on one node, so this sitting says something about the "
          "demand and nothing about the cluster. Recorded as the prereg's "
          "MN-H3 branch requires, not as a PASS.\n")
    elif v["h1"] == "PASS":
        w(f"\n**MN-H1 PASS** — {v['nodes']} distinct nodes carried work and "
          f"the busiest held {v['busiest']:.4f}, below the frozen 0.90 "
          "pinning threshold.\n")
    else:
        w(f"\n**MN-H1 FAIL** — {v['nodes']} node(s) carried work, busiest "
          f"share {v['busiest']:.4f} against a 0.90 threshold. The load "
          "pinned. That is a finding about this deployment and is published "
          "with the same prominence a PASS would have had.\n")

    w("\n## What this does and does not license\n")
    w("Every node here is a container on one machine sharing one kernel, one "
      "disk and one NIC. A PASS removes **single node** from W7's residue and "
      "leaves **single machine** standing — which §8 already lists as "
      "permanent. Nothing here kills a node, so nothing here speaks to "
      "failure behaviour, partitions or zones.\n")

    record_path(RECORD).write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"wrote {record_path(RECORD)}")
    print(f"MN-H1 {v['h1']} | MN-H2 {v['h2']} | nodes {v['nodes']} | "
          f"busiest {v['busiest']:.4f} | pods {v['pods']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
