"""PREREG_FAIR_J.md -> RESULTS_FAIR_J.md: the composite objective against fair
and tier-capable comparators, on fresh shared seeds.

FROZEN with the pre-registration; not edited after the run. Self-contained on
purpose: it imports only the shared J definition and the record path, so no
later edit to an exploratory script can change how this campaign is scored.

    python analysis_fair_j.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd
from scipy import stats as sps

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
from stats import composite_objective, holm_bonferroni, record_path  # noqa: E402

RESULTS = HERE.parents[1] / "eval" / "results"
DB = RESULTS / "raw_sim_fair_j.duckdb"
CSV = RESULTS / "metrics_matrix_fair_j.csv.gz"
RECORD = "RESULTS_FAIR_J.md"

TREATMENT = "jcac_converged"
PRIMARY = {"FJ-H1": "hpa_fair", "FJ-H2": "keda_fair", "FJ-H3": "jcac_nojoint_v2_tuned"}
SECONDARY = {"FJ-S1": "hpa_budget_tuned", "FJ-S2": "keda_budget_tuned"}
ALSO = "jcac_anchored"               # the published quotable controller, reported beside
DESIGN = ["workload", "tenant_mix", "cluster_size"]
REPS = 5
ALPHA = 0.05
NI_MARGIN = 0.05                     # inherited severity margin (EP/TP/BP/MM)
BOOT_N = 10_000
BOOT_SEED = 20260926
COLUMNS = ["system", "workload", "tenant_mix", "cluster_size", "rep", "total_cost_usd",
           "mean_violation", "mean_jain", "mean_excess", "tier_none_step_share"]


def load() -> pd.DataFrame:
    if DB.exists():
        import duckdb

        con = duckdb.connect(str(DB), read_only=True)
        try:
            df = con.execute(
                "select r.system, r.workload, r.tenant_mix, r.cluster_size, r.rep, "
                "m.total_cost_usd, m.mean_violation, m.mean_jain, m.mean_excess, "
                "m.tier_none_step_share from runs r join metrics m on r.run_id = m.run_id "
                "where r.status = 'valid'").fetchdf()
        finally:
            con.close()
        return df
    return pd.read_csv(CSV, float_precision="round_trip")[COLUMNS]


def complete_design_points(df: pd.DataFrame, arms: list[str]) -> pd.DataFrame:
    """Listwise: keep a design point only if every arm has all REPS valid
    reps there (PREREG_FAIR_J, stopping rule)."""
    counts = df[df.system.isin(arms)].groupby(DESIGN + ["system"]).size().unstack("system")
    ok = counts.reindex(columns=arms).fillna(0).ge(REPS).all(axis=1)
    keep = set(counts.index[ok])
    return df[[k in keep for k in zip(*(df[c] for c in DESIGN))]]


def design_diffs(df: pd.DataFrame, a: str, b: str, metric: str) -> np.ndarray:
    ma = df[df.system == a].groupby(DESIGN)[metric].mean()
    mb = df[df.system == b].groupby(DESIGN)[metric].mean()
    return (ma - mb).dropna().sort_index().to_numpy()


def boot_means(d: np.ndarray) -> np.ndarray:
    rng = np.random.default_rng(BOOT_SEED)
    return d[rng.integers(0, len(d), size=(BOOT_N, len(d)))].mean(axis=1)


def superiority(d: np.ndarray) -> dict:
    means = boot_means(d)
    p = float(sps.wilcoxon(d, alternative="less").pvalue) if np.any(d != 0) else 1.0
    return {"n": len(d), "mean": float(d.mean()), "dz": float(d.mean() / d.std(ddof=1)),
            "ci": (float(np.percentile(means, 2.5)), float(np.percentile(means, 97.5))),
            "p": p, "better": float((d < 0).mean())}


def noninferior(d: np.ndarray) -> dict:
    ucb = float(np.percentile(boot_means(d), 95.0))
    return {"mean": float(d.mean()), "ucb": ucb, "ni": ucb < NI_MARGIN}


def score(df: pd.DataFrame, family: dict[str, str]) -> dict[str, dict]:
    res = {hid: superiority(design_diffs(df, TREATMENT, comp, "J")) for hid, comp in family.items()}
    holm = holm_bonferroni({hid: r["p"] for hid, r in res.items()}, ALPHA)
    for hid, r in res.items():
        r["threshold"] = holm[hid]["threshold"]
        r["pass"] = bool(holm[hid]["reject"] and r["ci"][1] < 0)
    return res


def build(df: pd.DataFrame) -> str:
    arms = [TREATMENT, ALSO, *PRIMARY.values(), *SECONDARY.values()]
    n_all = df[DESIGN].drop_duplicates().shape[0]
    df = complete_design_points(df, arms)
    df = df.assign(J=composite_objective(df))
    n_dp = df[DESIGN].drop_duplicates().shape[0]
    prim, sec = score(df, PRIMARY), score(df, SECONDARY)
    L = ["# Composite objective against fair and tier-capable comparators, fresh shared seeds", "",
         "Generated by `analysis_fair_j.py`, frozen with `PREREG_FAIR_J.md`. Treatment `jcac_converged`; "
         f"unit: the design point (reps averaged); {n_dp} of {n_all} design points complete for every arm "
         f"(listwise rule). A PASS needs the one-sided Wilcoxon p at or below its Holm threshold AND the 95% "
         f"bootstrap CI of the mean difference entirely below 0 ({BOOT_N:,} resamples, seed {BOOT_SEED}). "
         "Negative = the treatment is better.", "",
         "## Per-arm means", "",
         "| arm | J | cost $ | mean_violation | mean_excess | Jain | AI shed (tier=none) |",
         "|---|---:|---:|---:|---:|---:|---:|"]
    for arm in arms:
        s = df[df.system == arm]
        L.append(f"| `{arm}` | {s.J.mean():.4f} | {s.total_cost_usd.mean():.4f} | {s.mean_violation.mean():.4f} | "
                 f"{s.mean_excess.mean():.4f} | {s.mean_jain.mean():.4f} | {s.tier_none_step_share.mean():.1%} |")

    def table(title: str, res: dict, family: dict) -> list[str]:
        out = ["", title, "",
               "| id | vs | design points | ΔJ | d_z | 95% CI of ΔJ | treatment better in | Wilcoxon p | "
               "Holm threshold | verdict |", "|---|---|---:|---:|---:|---|---:|---:|---:|---|"]
        for hid, r in res.items():
            out.append(f"| **{hid}** | `{family[hid]}` | {r['n']} | {r['mean']:+.4f} | {r['dz']:+.2f} | "
                       f"[{r['ci'][0]:+.4f}, {r['ci'][1]:+.4f}] | {r['better']:.0%} | {r['p']:.3g} | "
                       f"{r['threshold']:.4f} | {'PASS' if r['pass'] else 'FAIL'} |")
        return out

    L += table("## Confirmatory: FJ-H1..H3 (one Holm family of 3)", prim, PRIMARY)
    L += ["", "## SLO guard: `mean_excess` non-inferiority (one-sided 95% bootstrap bound < "
          f"{NI_MARGIN})", "", "| guard | vs | mean diff | 95% upper bound | verdict |", "|---|---|---:|---:|---|"]
    for hid, comp in PRIMARY.items():
        g = noninferior(design_diffs(df, TREATMENT, comp, "mean_excess"))
        L.append(f"| {hid}-NI | `{comp}` | {g['mean']:+.4f} | {g['ucb']:+.4f} | "
                 f"{'PASS' if g['ni'] else 'FAIL'} |")
    L += table("## Secondary: comparators carrying the budget rule (own Holm family of 2; not confirmatory)",
               sec, SECONDARY)
    L += ["", f"## Beside it: the published quotable controller `{ALSO}` (descriptive)", "",
          "| vs | ΔJ | 95% CI |", "|---|---:|---|"]
    for comp in [*PRIMARY.values(), *SECONDARY.values()]:
        r = superiority(design_diffs(df, ALSO, comp, "J"))
        L.append(f"| `{comp}` | {r['mean']:+.4f} | [{r['ci'][0]:+.4f}, {r['ci'][1]:+.4f}] |")
    L += ["", "## Per workload, treatment vs each primary comparator (descriptive)", "",
          "| workload | vs | ΔJ | treatment better in |", "|---|---|---:|---:|"]
    for comp in PRIMARY.values():
        ma = df[df.system == TREATMENT].groupby(DESIGN).J.mean()
        mb = df[df.system == comp].groupby(DESIGN).J.mean()
        d = (ma - mb).dropna()
        for wl, sub in d.groupby(level="workload"):
            L.append(f"| `{wl}` | `{comp}` | {sub.mean():+.4f} | {int((sub < 0).sum())}/{len(sub)} |")
    L.append("")
    return "\n".join(L) + "\n"


def main() -> int:
    out = record_path(RECORD)
    out.write_text(build(load()), encoding="utf-8")
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
