#!/usr/bin/env python3
"""PREREG_ORDER_PERMUTATION.md -> RESULTS_ORDER_PERMUTATION.md.

Adjudicates the audited fairness confound: the coordinate-descent sweep is
first-come-first-served on the shared cluster caps, and the published
`sorted()` order is confounded with priority class because tenant ids are
assigned by slot and every non-uniform mix puts the premium/whale tenants in
the low slots.

Decision rules are fixed by the pre-registration, committed before the run.
"""

from __future__ import annotations

import sys
from pathlib import Path

import duckdb
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent))
from stats import record_path  # noqa: E402

_RESULTS = Path(__file__).resolve().parents[2] / "eval" / "results"
DB = _RESULTS / "raw_sim_order_permutation.duckdb"
CSV = _RESULTS / "metrics_matrix_order_permutation.csv.gz"

PERMS = [f"jcac_perm{s}" for s in (1, 2, 3, 4, 5)]
PUBLISHED = "jcac"
SPREAD_THRESHOLD = 0.01   # OP-H2, frozen
COST_CV_THRESHOLD = 0.05  # OP-H3, frozen


def load() -> pd.DataFrame:
    cols = ("r.system, r.workload, r.tenant_mix, r.cluster_size, r.rep, "
            "m.total_cost_usd, m.mean_violation, m.mean_jain, m.mean_excess")
    if DB.exists():
        con = duckdb.connect(str(DB), read_only=True)
        df = con.execute(f"select {cols} from runs r join metrics m "
                         "on r.run_id = m.run_id where r.status = 'valid'").fetchdf()
        con.close()
        return df
    if CSV.exists():
        return pd.read_csv(CSV)
    raise FileNotFoundError(f"{DB.name} missing and export {CSV.name} absent")


def main() -> int:
    df = load()
    for arm in [PUBLISHED, *PERMS]:
        if arm not in set(df.system.unique()):
            print(f"missing arm {arm}; campaign incomplete", file=sys.stderr)
            return 1

    L = []
    w = L.append
    w("# Sweep-order permutation (V-series)\n")
    w("Generated by `analysis_order_permutation.py`. Pre-registration: "
      "`PREREG_ORDER_PERMUTATION.md`, committed before the campaign ran.\n")
    w("**No published result is replaced.** The published arm is `jcac` with "
      "`sorted()` order; the permutation arms are the identical controller "
      "under five fixed alternative orders (R1/R4).\n")

    # --- OP-H1: is sorted() inside the permutation range? -----------------
    w("\n## OP-H1 — is the published order inside the permutation range?\n")
    w("| mix | published Jain | perm min | perm max | published is |")
    w("|---|---:|---:|---:|---|")
    outside = []
    for mix in sorted(df.tenant_mix.unique()):
        sub = df[df.tenant_mix == mix]
        pub = sub[sub.system == PUBLISHED].mean_jain.mean()
        perm_means = [sub[sub.system == p].mean_jain.mean() for p in PERMS]
        lo, hi = min(perm_means), max(perm_means)
        if pub > hi:
            where, bad = "**ABOVE the range (most favorable)**", True
        elif pub < lo:
            where, bad = "below the range", True
        else:
            where, bad = "inside the range", False
        if bad:
            outside.append(mix)
        w(f"| {mix} | {pub:.4f} | {lo:.4f} | {hi:.4f} | {where} |")

    h1 = "FAIL" if outside else "PASS"
    w(f"\n**OP-H1 {h1}** — "
      + (f"the published order falls outside the permutation range on: "
         f"{', '.join(outside)}. The published fairness reading is a property "
         f"of the tenant naming scheme on those mixes."
         if outside else
         "the published order sits inside the range spanned by the "
         "permutations on every mix, so the fairness reading is not an "
         "artifact of tenant naming.") + "\n")

    # --- OP-H2: spread magnitude by mix -----------------------------------
    w("\n## OP-H2 — does order matter more where priority is heterogeneous?\n")
    w("| mix | Jain spread across the 6 orders | > 0.01 |")
    w("|---|---:|---|")
    spreads = {}
    for mix in sorted(df.tenant_mix.unique()):
        sub = df[df.tenant_mix == mix]
        means = [sub[sub.system == a].mean_jain.mean() for a in [PUBLISHED, *PERMS]]
        spread = max(means) - min(means)
        spreads[mix] = spread
        w(f"| {mix} | {spread:.4f} | {'yes' if spread > SPREAD_THRESHOLD else 'no'} |")
    whale_spread = spreads.get("whale", 0.0)
    h2 = "PASS" if whale_spread > SPREAD_THRESHOLD else "FAIL"
    w(f"\n**OP-H2 {h2}** — `whale` spread {whale_spread:.4f} "
      f"(threshold {SPREAD_THRESHOLD}).\n")

    # --- OP-H3: cost neutrality -------------------------------------------
    costs = [df[df.system == a].total_cost_usd.mean() for a in [PUBLISHED, *PERMS]]
    mean_cost = sum(costs) / len(costs)
    cv = (max(costs) - min(costs)) / mean_cost if mean_cost else 0.0
    h3 = "PASS" if cv < COST_CV_THRESHOLD else "FAIL"
    w("\n## OP-H3 — is cost order-dependent too?\n")
    w(f"- Cost spread across the six orders: **{cv * 100:.2f}%** of the mean "
      f"(threshold {COST_CV_THRESHOLD * 100:.0f}%)")
    w(f"\n**OP-H3 {h3}** — "
      + ("cost is essentially order-independent, so the cost comparison does "
         "not inherit this confound."
         if h3 == "PASS" else
         "cost is order-dependent, so the headline cost comparison inherits "
         "the confound as well and must be reported with the permutation "
         "spread.") + "\n")

    # --- Full per-arm table ------------------------------------------------
    w("\n## Per-order results (all cells pooled)\n")
    w("| arm | mean_jain | total_cost_usd | mean_violation | mean_excess |")
    w("|---|---:|---:|---:|---:|")
    for arm in [PUBLISHED, *PERMS]:
        s = df[df.system == arm]
        label = f"`{arm}`" + (" *(published, sorted)*" if arm == PUBLISHED else "")
        w(f"| {label} | {s.mean_jain.mean():.4f} | {s.total_cost_usd.mean():.4f} "
          f"| {s.mean_violation.mean():.4f} | {s.mean_excess.mean():.4f} |")

    w("\n## What this means\n")
    if outside:
        w("The sweep order is a free parameter that was never varied, and it "
          "is confounded with priority class: tenant ids are assigned by slot "
          "and the mixes place premium and whale tenants in the low slots, so "
          "`sorted()` lets the largest tenants claim contended capacity first. "
          "**Every published fairness number must therefore be reported with "
          "this permutation spread**, and the sweep order named as a "
          "controller parameter rather than an implementation detail.\n")
    else:
        w("The published order sits inside the permutation range on every mix "
          "tested, so the fairness results are not an artifact of the tenant "
          "naming scheme. The spread is reported here so future fairness "
          "claims can cite it rather than assume it.\n")

    out = record_path("RESULTS_ORDER_PERMUTATION.md")
    out.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
