"""Tier-price break-even at the CORRECTED GPU corner (PREREG_TIER_RATIO_V2.md).

The accounting reading, re-asked. `breakeven_tier.py` froze
`R_LARGE = [5.0 .. 100.0]` and a `GPU_CORNER` of (1.52, 16.6). That corner's
large coordinate was a CPU-offload artifact: a 16 GB card could not hold
Qwen2.5-7B at fp16 and `device_map="auto"` spilled layers to host memory.
Re-measured on GPU T4 x2 with zero modules offloaded, the corner is
(1.475, 1.518) -- which sits 3.3x below the smallest r_large the frozen grid
contains, so the true corner was never evaluated.

This script does NOT modify `breakeven_tier.py`, which stays frozen. It
**imports its algebra** -- `load_rows` and `reprice` -- so the arithmetic is
identical by construction and only the grid differs. The v2 grid is a strict
SUPERSET of v1's, so every v1 point stays evaluable and v1's finding is
re-derivable here.

Exploratory, as v1 was: decisions stay fixed at what each controller chose
under the published economy. The controllers-re-decide reading is the
pre-registered matrix rerun (`matrix_gpu_econ_v2.yaml`).
"""

from __future__ import annotations

import stats
from breakeven_tier import (  # frozen algebra, imported not reimplemented
    CAMPAIGNS,
    CELL,
    IDENTITY_TOL_USD,
    PUBLISHED,
    load_rows,
    reprice,
)

# Frozen in PREREG_TIER_RATIO_V2.md -- do not extend after execution.
# Superset of v1's grid; the two new low-end coordinates are the corrected
# measurement itself plus one intermediate point per axis.
R_MID = [1.475, 1.52, 3.0, 5.0, 10.0]
R_LARGE = [1.518, 2.5, 5.0, 10.0, 16.6, 33.0, 100.0]
LEVEL = [0.2, 1.0, 5.0]

GPU_CORNER_V1 = (1.52, 16.6, 1.0)          # superseded: offload-dominated
GPU_CORNER_CORRECTED = (1.475, 1.518, 1.0)  # tier_bench_t4.csv, 0 offloaded

# Written through stats.record_path so POLYFORGE_ANALYSIS_OUT can redirect
# it; resolving against __file__ would overwrite the committed record and
# leave the reproduction gate nothing to compare against.
OUT = stats.record_path("BREAKEVEN_TIER_V2.md")


def main() -> None:
    lines: list[str] = []
    w = lines.append
    w("# Tier-price break-even at the corrected GPU corner — EXPLORATORY")
    w("")
    w("Generated by `breakeven_tier_v2.py`; grid and rules frozen in")
    w("`PREREG_TIER_RATIO_V2.md`. Algebra is imported from the frozen")
    w("`breakeven_tier.py`, so only the grid differs. Decisions stay fixed at")
    w("what each controller chose under the published 1:10:100 economy — the")
    w("*accounting* reading. **No confirmatory claim derives from this file**;")
    w("the controllers-re-decide reading is the pre-registered")
    w("`matrix_gpu_econ_v2.yaml` rerun. Rep-0 rows, descriptive only.")
    w("")
    w("`GPU corner v1` = (1.52, 16.6) is the superseded offload-dominated")
    w("corner v1 tested. `GPU corner CORRECTED` = (1.475, 1.518) is the")
    w("measurement from `tier_bench_t4.csv` (all three tiers on GPU T4 x2,")
    w("`modules offloaded to cpu/disk: 0`). Both are shown so the effect of the")
    w("correction is legible rather than asserted.")
    w("")

    for spec in CAMPAIGNS:
        rows = load_rows(spec["source"])
        per_run = (
            rows.groupby(["run_id", "system", "workload", "tenant_mix",
                          "cluster_size", "tier"], as_index=False)
            [["infra_usd", "tier_usd"]].sum()
        )
        recorded = rows.groupby("run_id").cost_usd.sum()

        repriced_pub = reprice(per_run, *PUBLISHED)
        gap = (repriced_pub - recorded).abs()
        assert gap.max() < IDENTITY_TOL_USD, (
            f"{spec['source']}: identity check failed, max gap {gap.max():.6f} USD"
        )

        ident = per_run.groupby("run_id").first()[
            ["system", "workload", "tenant_mix", "cluster_size"]
        ]
        treatment = spec["treatment"]

        w(f"## {spec['name']} — `{spec['source']}`, rep-0 rows, "
          f"identity check max gap {gap.max():.2e} USD")
        w("")

        grid_totals = {}
        for r_mid in R_MID:
            for r_large in R_LARGE:
                for s in LEVEL:
                    grid_totals[(r_mid, r_large, s)] = reprice(
                        per_run, r_mid, r_large, s)

        w(f"Grid: {len(R_MID)}x{len(R_LARGE)}x{len(LEVEL)} = "
          f"{len(grid_totals)} price vectors.")
        w("")
        w("| baseline | published | GPU corner v1 (superseded) | "
          "GPU corner CORRECTED | worst grid point | flips |")
        w("|---|---|---|---|---|---|")

        for baseline in spec["baselines"]:
            def cell_stats(point):
                totals = grid_totals[point]
                frame = ident.assign(total=totals).reset_index()
                t = frame[frame.system == treatment]
                b = frame[frame.system == baseline]
                m = t.merge(b, on=CELL, suffixes=("_t", "_b"))
                delta = (m.total_t - m.total_b) / m.total_b
                cheaper = int((m.total_t < m.total_b).sum())
                agg = float((m.total_t.sum() - m.total_b.sum()) / m.total_b.sum())
                return cheaper, len(m), float(delta.mean()), agg

            def fmt(st):
                return (f"{st[0]}/{st[1]}, cell-mean {st[2]:+.1%}, "
                        f"agg {st[3]:+.1%}")

            pub = cell_stats(PUBLISHED)
            g1 = cell_stats(GPU_CORNER_V1)
            g2 = cell_stats(GPU_CORNER_CORRECTED)

            worst_point, worst = None, None
            flips_agg = []
            for point in grid_totals:
                st = cell_stats(point)
                if worst is None or st[3] > worst[3]:
                    worst_point, worst = point, st
                if st[3] > 0:
                    flips_agg.append((point, st[3]))

            flip_desc = ("none in grid" if not flips_agg else
                         ", ".join(f"{p} {v:+.1%}" for p, v in flips_agg[:4])
                         + (f" (+{len(flips_agg) - 4} more)"
                            if len(flips_agg) > 4 else ""))

            w(f"| {baseline} | {fmt(pub)} | {fmt(g1)} | **{fmt(g2)}** | "
              f"{worst_point} {worst[3]:+.1%} | {flip_desc} |")
        w("")

    w("## Reading")
    w("")
    w("The column that matters is **GPU corner CORRECTED**. Where it tracks the")
    w("v1 column, the correction changed nothing and v1's conclusion transfers.")
    w("Where it diverges, the divergence is the finding: v1 priced `large` at")
    w("16.6x when the hardware says 1.518x, so any advantage that depended on")
    w("an expensive large tier is overstated by v1 and is corrected here.")
    w("Aggregate sign flips, if any, are listed verbatim — including them is")
    w("the point. All of this holds decisions fixed.")
    w("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
