"""Replica churn of every B1' arm, recovered from the committed evidence
-> CHURN_WAVE4_CALIBRATED.md.

Descriptive, no hypothesis. The corrected joint controller wins on cost at
iso-fairness (RESULTS_WAVE4_CALIBRATED.md); this record shows HOW it runs
the replica knob, because the evidence also shows it oscillating: the guard
amendment (PREREG_WAVE4_CALIBRATED.md, Amendment 1) exists because pods the
controller created were shed within a control step. A reader of the result
should see the replica trajectory, not just the bill.

Sources, per run, under wave4_calibrated_plane_evidence/runs/:
- eval-export-fine.json: `cost_infra_usd` per 10-s bucket is the replica
  sampler's reading for that bucket (one `.status.replicas` sample every
  REPLICA_SAMPLE_S seconds priced at REPLICA_COST_USD_HR), so the replica
  count per sample is exact: cost / (price per replica-sample).
- load_distribution.json: `presence` -- how many 30-s `kubectl top` samples
  each control-plane pod appeared in; pods seen in fewer than 3 are the
  ones created and shed inside a minute.

    python churn_wave4_calibrated.py
"""

from __future__ import annotations

import importlib.util
import json
import statistics
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
from stats import record_path  # noqa: E402

_spec = importlib.util.spec_from_file_location("aw", HERE / "analysis_wave4_calibrated.py")
aw = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(aw)

REPLICA_COST_USD_HR = 0.048   # eval/harness/cluster_backend.py
REPLICA_SAMPLE_S = 10.0       # ReplicaSampler(interval_s=10.0)
PRICE_PER_REPLICA_SAMPLE = REPLICA_COST_USD_HR / 3600.0 * REPLICA_SAMPLE_S
SHORT_LIVED_SAMPLES = 3       # MIN_PRESENCE_SAMPLES in the harness


def trajectory(arm: str, cell: str, rep: int) -> list[int] | None:
    """Replica count per sampled bucket inside the load window, in order."""
    d = aw.run_dir(arm, cell, rep)
    p = d / "eval-export-fine.json"
    if not p.exists():
        return None
    buckets = json.loads(p.read_text(encoding="utf-8")).get("buckets") or []
    if not buckets or "cost_infra_usd" not in buckets[0] or "n_events" not in buckets[0]:
        return None
    floor = aw.WINDOW_EVENT_FRACTION * sorted(int(b["n_events"]) for b in buckets)[len(buckets) // 2]
    idx = [i for i, b in enumerate(buckets) if int(b["n_events"]) >= floor]
    if not idx:
        return None
    window = buckets[idx[0]:idx[-1] + 1]
    return [round(b["cost_infra_usd"] / PRICE_PER_REPLICA_SAMPLE) for b in window if b["cost_infra_usd"] > 0]


def pods(arm: str, cell: str, rep: int) -> tuple[int, int] | None:
    p = aw.run_dir(arm, cell, rep) / "load_distribution.json"
    if not p.exists():
        return None
    presence = json.loads(p.read_text(encoding="utf-8")).get("presence") or {}
    if not presence:
        return None
    return len(presence), sum(1 for v in presence.values() if v < SHORT_LIVED_SAMPLES)


def describe(arm: str, cell: str, rep: int) -> dict | None:
    t = trajectory(arm, cell, rep)
    if not t:
        return None
    changes = [b - a for a, b in zip(t, t[1:]) if b != a]
    pd_ = pods(arm, cell, rep) or (None, None)
    return {"arm": arm, "cell": cell, "rep": rep, "samples": len(t),
            "min": min(t), "max": max(t), "mean": statistics.fmean(t),
            "changes": len(changes), "ups": sum(1 for c in changes if c > 0),
            "downs": sum(1 for c in changes if c < 0),
            "largest": max((abs(c) for c in changes), default=0),
            "replica_seconds": sum(t) * REPLICA_SAMPLE_S,
            "pods": pd_[0], "short": pd_[1]}


def build() -> str:
    df = aw.load()
    reps = sorted(int(r) for r in df.rep.unique())
    # Only (arm, cell, rep) combinations the scored table calls valid. Checking
    # the arm alone let a FAILED run's folder through, and that folder held a
    # copy of another run's export (audit 2026-09-26, HIGH-4).
    valid = {(str(s), str(w), int(r)) for s, w, r in zip(df.system, df.workload, df.rep)}
    rows = [r for cell in aw.CELLS for arm in aw.ARMS for rep in reps
            if (arm, cell, rep) in valid for r in [describe(arm, cell, rep)] if r]
    prim = [r for r in rows if r["cell"] == aw.PRIMARY_CELL and r["arm"] == aw.TREATMENT]
    L = ["# B1′ — how each arm ran the replica knob (churn, from the committed evidence)", "",
         "Generated by `churn_wave4_calibrated.py` from the per-run fine exports (replica count per 10-s sample, "
         "recovered exactly from `cost_infra_usd`) and load distributions (per-pod presence) under "
         "`eval/results/wave4_calibrated_plane_evidence/runs/`. Descriptive: no hypothesis, no verdict.", "",
         "## Why this record exists", "",
         "The corrected joint controller wins on cost at iso-fairness. The same evidence shows it oscillating: pods it "
         "created were shed inside a control step (Amendment 1 of the pre-registration exists for that). The replica "
         "trajectory of every run is printed here so the win is read with its operating behaviour, not just its bill. "
         + (f"In `{aw.PRIMARY_CELL}` the calibrated arm changed its replica count at "
            f"{' and '.join(str(r['changes']) for r in prim)} of its {' and '.join(str(r['samples']) for r in prim)} "
            f"steps in the two reps, by up to {max(r['largest'] for r in prim)} replicas in one step, between "
            f"{min(r['min'] for r in prim)} and {max(r['max'] for r in prim)} replicas; the published controller and "
            f"the single-knob arms are in the table."
            if prim else ""), "",
         "## Every run", "",
         "`changes` counts replica-count changes between consecutive 10-s samples inside the load window; `largest` "
         "is the biggest single change; `pods` is how many distinct control-plane pods `kubectl top` saw during the "
         f"window and `short` how many of them appeared in fewer than {SHORT_LIVED_SAMPLES} of its 30-s samples "
         "(created and shed inside a minute). Only runs the scored table marks valid are listed: the folder of a "
         "failed run can hold another run's files (a harness defect fixed on 2026-09-26), so it is not evidence "
         "of that run.", "",
         "| cell | arm | rep | samples | replicas min..max (mean) | changes (up / down) | largest | replica-seconds | pods | short-lived |",
         "|---|---|---|---|---|---|---|---|---|---|"]
    for r in rows:
        L.append(f"| {r['cell']} | {r['arm']} | {r['rep']} | {r['samples']} | {r['min']}..{r['max']} ({r['mean']:.1f}) | "
                 f"{r['changes']} ({r['ups']} / {r['downs']}) | {r['largest']} | {r['replica_seconds']:.0f} | "
                 f"{r['pods'] if r['pods'] is not None else 'n/a'} | {r['short'] if r['short'] is not None else 'n/a'} |")
    L += ["", "## Reading", "",
          "* The single-knob arms without the replica knob (`cache-only`, `tier-only`) hold the chart's initial "
          "replica count for the whole window; their infra cost is the ceiling every replica-aware arm is measured "
          "against.",
          "* The published controller (`jcac`) moves replicas rarely and upward: its plant model is pessimistic and "
          "its switching penalty exceeds the saving of shedding a replica (the ratchet the correction removed).",
          "* The corrected controller (`jcac-calibrated`) changes its replica count at most steps, and in the two "
          "AI-heavy cells by large jumps: in `tier_mixed` it swings between 8 and 24 replicas with single-step "
          "changes of 9–11, in `joint_stress` between 9 and 16 with changes of 3–4. That is a limit cycle, not a "
          "dither. A plausible mechanism, not measured here: the realized AI p95 moves from step to step (tier "
          "latency under load), the additive tier-latency offset learns UP fast (0.5) and DOWN slowly (0.1), the "
          "projection flips between predicting a violation (add replicas) and predicting headroom (shed them), and "
          "the half-replica switching penalty is too small to hold the plan still. Whether the replica count moves "
          "the AI p95 at all on this plant is not established by this record. Its mean replica-"
          "seconds are still below the static arms' (the cost the record scores), and its Jain index and violation "
          "are unchanged, so the win stands as registered; what the cycle costs in pod creations is visible here and "
          "not in the objective. A dwell time or a rate limit on the replica knob is the obvious damping; neither "
          "is in this sitting, and adding one needs a new pre-registration and a sitting to score it.",
          "* `replica-only` (HPA) scales on CPU alone and, in the AI-heavy cells, cannot reduce tier spend at all; its "
          "replica trajectory is printed for completeness. In this sitting its tenant `t00` also ran on the `large` "
          "tier with the cache at 0 MB: that is the WL-H2 preflight's last probe posture, which the harness did not "
          "restore for non-operator arms (found 2026-09-26; fixed in `prepare_live_ai_knobs`). Its cost here is "
          "therefore not a measurement of a replica-only controller.", ""]
    return "\n".join(L) + "\n"


def main() -> int:
    out = record_path("CHURN_WAVE4_CALIBRATED.md")
    out.write_text(build(), encoding="utf-8")
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
