"""Erratum: Phase 7 and the live-chaos sitting ran with a planner that read zero
demand -> ERRATUM_ZERO_DEMAND_PLANNER.md.

Descriptive, no hypothesis. Found by the audit of 2026-09-26 in the message of
commit 33bd83c (2026-08-08): "RPSWindow was never populated by any production
emitter, so the live planner read zero demand for every tenant and the
controller held its initial configuration for whole runs." The records that
predate that fix do not say so. The verdict records stand as committed; this
record states, from their own run tables, what they measured.

    python erratum_zero_demand_planner.py
"""

from __future__ import annotations

import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

import pandas as pd

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
from stats import record_path  # noqa: E402

RESULTS = HERE.parents[1] / "eval" / "results"
RECORD = "ERRATUM_ZERO_DEMAND_PLANNER.md"
PHASE7_RUNS = RESULTS / "phase7_live_runs.csv"
CHAOS_RUNS = RESULTS / "live_chaos_p99_runs.csv"
LAPTOP_OFFSET_H = 6   # harness 1.0.0 rows hold the laptop's local time (UTC+6)

FIX_COMMIT = "33bd83c"
FIX_UTC = datetime(2026, 8, 8, 11, 26, 42, tzinfo=timezone.utc)
# Records' first commits (verified against git by test_erratum_zero_demand_planner).
FIRST_COMMIT = {
    "PHASE7_ORDINAL.md": ("2026-07-16", "6c68766"),
    "RESULTS_LIVE_CHAOS_P99.md": ("2026-07-19", "56c329f"),
    "RESULTS_LIVE_SOAK_V8.md": ("2026-08-30", "8b28e7b"),
    "RESULTS_TRACE_LIVE.md": ("2026-09-01", "929df84"),
    "RESULTS_MULTINODE.md": ("2026-09-05", "fc47133"),
    "RESULTS_WAVE4_LIVE_PLANE.md": ("2026-08-30", "7f0a392"),
    "RESULTS_WAVE4_CALIBRATED.md": ("2026-09-16", "880f6f6"),
}


def offset_hours(harness_version: str) -> int:
    """Hours to subtract from a stored `recorded_at` for UTC: harness 1.0.0
    stored the laptop's local time (UTC+6); >= 1.1.0 stores UTC."""
    try:
        version = tuple(int(p) for p in str(harness_version).split("."))
    except ValueError:
        version = (0,)
    return 0 if version >= (1, 1, 0) else LAPTOP_OFFSET_H


def phase7() -> dict:
    df = pd.read_csv(PHASE7_RUNS)
    local = pd.to_datetime(df.recorded_at)
    utc = [t.to_pydatetime().replace(tzinfo=timezone.utc) - timedelta(hours=offset_hours(v))
           for t, v in zip(local, df.harness_version)]
    cells = []
    for (system, workload), sub in df.groupby(["system", "workload"], sort=True):
        cells.append({"system": system, "workload": workload,
                      "valid": int((sub.status == "valid").sum()), "runs": len(sub)})
    return {"first": min(utc), "last": max(utc), "valid": int((df.status == "valid").sum()),
            "runs": len(df), "cells": cells}


def build() -> str:
    p7 = phase7()
    chaos = pd.read_csv(CHAOS_RUNS)
    before = p7["last"] < FIX_UTC
    L = ["# Erratum: Phase 7 and the live-chaos sitting ran with a planner that read zero demand", "",
         "Generated by `erratum_zero_demand_planner.py` from the committed run tables "
         "(`eval/results/phase7_live_runs.csv`, `eval/results/live_chaos_p99_runs.csv`). Descriptive: no "
         "hypothesis, no verdict. The verdict records stand as committed.", "",
         "## Mechanism", "",
         f"Commit `{FIX_COMMIT}` ({FIX_UTC:%Y-%m-%d %H:%M} UTC) records the defect and fixes it: the live "
         "demand window (`RPSWindow`) was never populated by any production emitter, so the live planner "
         "read zero demand for every tenant and the controller held its initial configuration for whole "
         "runs. Every live record committed before that fix measured the joint controller's INITIAL "
         "configuration, not its plans.", "",
         "## Which live records predate the fix", "",
         "| record | first committed | commit | before the fix? |", "|---|---|---|---|"]
    for name, (day, sha) in FIRST_COMMIT.items():
        pre = datetime.fromisoformat(day).replace(tzinfo=timezone.utc) < FIX_UTC
        L.append(f"| `{name}` | {day} | `{sha}` | {'**yes**' if pre else 'no'} |")
    L += ["", "## Phase 7 (`PHASE7_ORDINAL.md`)", "",
          f"The run table dates every run between {p7['first']:%Y-%m-%d %H:%M} and {p7['last']:%Y-%m-%d %H:%M} "
          f"UTC (laptop local time, UTC+{LAPTOP_OFFSET_H}): "
          + ("all before the fix." if before else "NOT all before the fix; read the table.")
          + f" **{p7['valid']} of {p7['runs']}** runs are valid, not 12 of 12:", "",
          "| arm | cell | valid / runs |", "|---|---|---|"]
    for c in p7["cells"]:
        L.append(f"| `{c['system']}` | `{c['workload']}` | {c['valid']} / {c['runs']} |")
    L += ["", "So the Phase 7 `jcac` arm held its initial configuration for the whole of every run. Its "
          "ordinal comparison is \"JCAC's starting configuration against real HPA\", and the DISAGREE "
          "verdict, which stands as recorded, is not evidence about the controller's plans. The "
          "`crud_bursty` cell rests on one valid `jcac` run.", "",
          "## Live chaos (`RESULTS_LIVE_CHAOS_P99.md`, LC-H1)", "",
          f"The sitting predates the fix, so the \"last-known-good plan\" the record credits with absorbing "
          f"the planner crash and the API-server throttle was the initial configuration: the planner had "
          f"never made a plan. The recorded `mean_violation` is "
          f"{', '.join(f'{v:g}' for v in chaos.mean_violation)} in the {len(chaos)} cells, against a target "
          "the data plane stays far below. As scored, LC-H1 could not have failed. Its PASS stands as "
          "recorded and shows that the data plane served through the faults, not that a planner fallback "
          "carried a plan.", "",
          "## What this changes", "",
          "* Any claim that Phase 7 shows \"the full loop runs live — features to planner to operator\" is "
          "not supported by these runs.",
          "* LC-H1 is a demonstration that the data plane survives the faults, not a test of the controller's "
          "fallback.",
          "* The live records from 2026-08-30 onward (soak V8, trace live, multinode, B1, B1′, B1″) post-date "
          "the fix and are not affected by this defect.", ""]
    return "\n".join(L) + "\n"


def main() -> int:
    out = record_path(RECORD)
    out.write_text(build(), encoding="utf-8")
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
