"""Erratum: the replica-only arm of B1 and B1' ran with one tenant on the
largest tier and no cache -> ERRATUM_WAVE4_REPLICA_ONLY.md.

Descriptive, no hypothesis. Found by the audit of 2026-09-26. The WL-H2 knob
preflight probes tenant t00 and its LAST write pins t00 to the largest tier
with the cache at 0 MB. Operator arms get their Policy knobs re-pushed when
the reconciler resumes. The non-operator replica-only arm had its default
knobs pushed BEFORE the probe and never again, so t00 served the scored window
on the largest tier with no cache. Fixed in eval/harness/cluster_backend.py
(`prepare_live_ai_knobs`: defaults pushed after the probe, then read back).

The verdict records stand as committed; this record states, from their own
evidence, which of their readings measured a misconfigured arm.

    python erratum_wave4_replica_only.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import pandas as pd

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
from stats import record_path  # noqa: E402

RESULTS = HERE.parents[1] / "eval" / "results"
B1P_EVIDENCE = RESULTS / "wave4_calibrated_plane_evidence"
B1P_RUNS = RESULTS / "wave4_calibrated_plane_runs.csv"
B1_RUNS = RESULTS / "wave4_live_plane_runs.csv"
AI_CELLS = ("ai_cacheable", "tier_mixed", "joint_stress")
AFFECTED = "replica-only"


def _valid(path: Path) -> pd.DataFrame:
    df = pd.read_csv(path, float_precision="round_trip")
    return df[df.status == "valid"]


def load_b1p() -> pd.DataFrame:
    return _valid(B1P_RUNS)


def load_b1() -> pd.DataFrame:
    return _valid(B1_RUNS)


def export(arm: str, cell: str, rep: int) -> dict | None:
    p = B1P_EVIDENCE / "runs" / f"{arm}__{cell}__uniform__small__rep{rep}" / "eval-export.json"
    return json.loads(p.read_text(encoding="utf-8")) if p.exists() else None


def b1p_rows(runs: pd.DataFrame) -> list[dict]:
    rows = []
    for cell in AI_CELLS:
        for arm, rep in sorted({(str(a), int(r)) for a, w, r in
                                zip(runs.system, runs.workload, runs.rep) if w == cell}):
            e = export(arm, cell, rep)
            if e is None:
                continue
            rows.append({"cell": cell, "arm": arm, "rep": rep,
                         "large": int((e.get("tier_requests") or {}).get("large", 0)),
                         "hit": float(e.get("cache_hit_rate", 0.0)),
                         "cost": float(e.get("total_cost_usd", 0.0))})
    return rows


def build() -> str:
    rows = b1p_rows(load_b1p())
    others = sorted({r["large"] for r in rows if r["arm"] != AFFECTED})
    affected = [r for r in rows if r["arm"] == AFFECTED]
    probe = max(others) if others else 0
    contaminated = bool(affected) and all(r["large"] > 10 * max(probe, 1) for r in affected)
    L = ["# Erratum: the replica-only arm of B1 and B1′ ran misconfigured", "",
         "Generated by `erratum_wave4_replica_only.py` from the committed per-run exports under "
         "`eval/results/wave4_calibrated_plane_evidence/runs/` and the committed run tables. Descriptive: no "
         "hypothesis, no verdict. The verdict records stand as committed; this record says which of their "
         "readings measured a misconfigured arm.", "",
         "## Mechanism", "",
         "The WL-H2 knob preflight probes tenant `t00`, and its last write pins `t00` to the largest tier with the "
         "cache at 0 MB. Operator arms (`jcac`, `jcac-calibrated`, `cache-only`, `tier-only`) have their Policy "
         "knobs re-pushed when the reconciler resumes. The non-operator `replica-only` arm had its default knobs "
         "pushed before the probe and never again, so `t00` served the scored window on the largest tier with no "
         "cache. Found by the audit of 2026-09-26 and fixed in `eval/harness/cluster_backend.py` "
         "(`prepare_live_ai_knobs` pushes the defaults after the probe and reads them back).", "",
         "## Evidence: B1′, every valid run in the AI cells", "",
         "| cell | arm | rep | large-tier requests | cache hit rate | total cost $ |",
         "|---|---|---|---:|---:|---:|"]
    for r in rows:
        L.append(f"| {r['cell']} | {r['arm']} | {r['rep']} | {r['large']} | {r['hit']:.3f} | {r['cost']:.4f} |")
    L += ["", "## Finding", ""]
    if contaminated:
        span = f"{min(r['large'] for r in affected)}–{max(r['large'] for r in affected)}"
        L.append(f"**CONTAMINATED.** In every AI-cell run `{AFFECTED}` sent {span} requests to the largest tier; "
                 f"every other arm sent {probe}, which is the preflight probe's own traffic. Its cache hit rate is "
                 f"one tenant's worth below the others'. `{AFFECTED}`'s costs in these cells are not a measurement "
                 "of a replica-only controller.")
    else:
        L.append(f"**NOT OBSERVED.** In the exports read here `{AFFECTED}`'s largest-tier traffic is not "
                 "distinguishable from the other arms'.")
    b1 = load_b1()
    if len(b1):
        L += ["", "## B1 (costs only)", "",
              "B1 kept only the last run's export, so its tier split cannot be shown. It ran the same harness path, "
              "and its costs show the same pattern:", "",
              "| cell | replica-only $ | other arms $ (min–max) |", "|---|---:|---|"]
        for cell in sorted(set(b1.workload)):
            c = b1[b1.workload == cell]
            ro = c[c.system == AFFECTED].total_cost_usd
            ot = c[c.system != AFFECTED].total_cost_usd
            if len(ro) and len(ot):
                L.append(f"| {cell} | {ro.mean():.4f} | {ot.min():.4f}–{ot.max():.4f} |")
    L += ["", "## What this changes", "",
          "* `RESULTS_WAVE4_CALIBRATED.md`: the WL-H1′ comparison against `replica-only` (−99.0%) measured a "
          "misconfigured arm and is not evidence about a replica-only controller. The comparisons against `jcac`, "
          "`cache-only` and `tier-only` are operator arms and are unaffected.",
          "* `RESULTS_WAVE4_LIVE_PLANE.md`: its `replica-only` rows carry the same defect.",
          "* A replica-only live comparison needs a new sitting on the fixed harness, under a new registration.", ""]
    return "\n".join(L) + "\n"


def main() -> int:
    out = record_path("ERRATUM_WAVE4_REPLICA_ONLY.md")
    out.write_text(build(), encoding="utf-8")
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
