"""Wave 3 live chaos + p99: score the committed live data against the frozen readings.

PROTOCOL — the readings implemented here were frozen in PREREG_LIVE_CHAOS_P99.md
(registered 2026-07-16, session 20, pushed before any live number existed). The
live sitting ran in session 23 (Codespace, shared-PG data plane); the run-level
record was committed as `eval/results/live_chaos_p99_runs.csv` (commit 7bdbd4f)
with no RESULTS document. This script is that document's generator — it adds no
new measurement and no new reading.

- Input: `eval/results/live_chaos_p99_runs.csv` (run-level; the per-step series
  and raw duckdbs are gitignored and travel in the Zenodo bundle).
- LC-H1 (qualitative, pre-committed): mean_violation returns to within
  CHAOS_TOL = 0.05 of its pre-fault level within 5 minutes of each fault
  clearing. Read from the committed record: violation is non-negative, so a
  run-level mean of 0 over all steps implies every step is 0 — no excursion
  existed to recover from. Any nonzero mean would make this reading
  indeterminate at run level and the script says so rather than passing it.
- P99-H1 (descriptive, no pass/fail): live p95 and p99 side by side per
  request family per cell, with the p99/p95 ratio; state whether the p99
  violation verdict matches the p95 verdict.
- Ground rule 5: p99 is a live-only number; nothing here is compared to or
  back-fitted into any sim table.

One run of this script per the prereg's stopping rule; results to
RESULTS_LIVE_CHAOS_P99.md.

    python live_chaos_p99.py
"""

from __future__ import annotations

import csv
from pathlib import Path

import stats  # noqa: E402  (research/analysis/stats.py)

ROOT = Path(__file__).resolve().parents[2]
CSV = ROOT / "eval" / "results" / "live_chaos_p99_runs.csv"
# Written through stats.record_path like every other generator. It used to
# resolve to this directory unconditionally, which meant the committed
# record was the ONLY place it could write: running the script overwrote
# the published record, and scripts/reproduce.py could not regenerate it
# into a scratch directory to compare. Both problems, one line.
OUT = stats.record_path("RESULTS_LIVE_CHAOS_P99.md")

CHAOS_TOL = 0.05
STEP_SECONDS = 10


def main() -> None:
    with CSV.open(newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))

    lines: list[str] = []
    w = lines.append
    w("# Wave 3 live chaos + p99 — results against the frozen readings")
    w("")
    w("Generated by `live_chaos_p99.py` from the committed run-level record")
    w("`eval/results/live_chaos_p99_runs.csv` (session 23 live sitting, commit")
    w("7bdbd4f). Protocol: `PREREG_LIVE_CHAOS_P99.md`, pushed 2026-07-16 before")
    w("any live number existed. This file adds no new measurement.")
    w("")
    w("## Substrate, as run (disclosures)")
    w("")
    w("- jcac arm only, one execution per cell — a demonstration that the")
    w("  designed fallback works over the wire, not a powered comparison")
    w("  (scoped so in the prereg).")
    w("- **Shared-PG data plane:** the session-23 sitting ran the control plane")
    w("  against a shared PostgreSQL data plane rather than the session-19")
    w("  per-pod fixture — the substrate deviation that made the Codespace run")
    w("  fit its quota. Fault injections, offsets, and cell geometry are the")
    w("  frozen ones.")
    w("- The `ai_cacheable` row is the fault-free smoke (Part B p99 source for")
    w("  that cell); both chaos faults ran on the `crud_bursty` cell, per row.")
    w("")
    w("## Run table (committed record, verbatim)")
    w("")
    w("| cell | steps | faults | mean_violation | jain | cost $ | crud p95/p99 ms | ai p95/p99 ms |")
    w("|---|---|---|---|---|---|---|---|")
    for r in rows:
        w(
            f"| {r['cell']} | {r['steps']} | {r['faults']} | "
            f"{float(r['mean_violation']):.4f} | {float(r['mean_jain']):.4f} | "
            f"{float(r['total_cost_usd']):.4f} | "
            f"{float(r['crud_p95_ms']):.4f} / {float(r['crud_p99_ms']):.4f} | "
            f"{float(r['ai_p95_ms']):.4f} / {float(r['ai_p99_ms']):.4f} |"
        )
    w("")

    w("## Part A — LC-H1 (planner crash + apiserver throttle)")
    w("")
    chaos = [r for r in rows if r["faults"] != "none"]
    for r in chaos:
        steps = int(r["steps"])
        viol = float(r["mean_violation"])
        minutes = steps * STEP_SECONDS / 60
        w(f"- Cell `{r['cell']}`: {r['faults']} over {steps} steps")
        w(f"  (~{minutes:.1f} min at {STEP_SECONDS} s/step).")
        if viol == 0.0:
            w(
                "- Run-level mean_violation is **0.0000**. Violation is"
                " non-negative, so a zero mean over all"
                f" {steps} steps implies **every step is zero** — including"
                " the planner-crash window at T=8 min and the 60 s APF"
                " throttle at T=14 min. There was no violation excursion to"
                " recover from: the last-known-good plan hold carried both"
                " faults at zero violation under the cell's burst load."
            )
            w(
                f"- **LC-H1 PASS** (strongest form): the post-fault level"
                f" equals the pre-fault level exactly, trivially within"
                f" CHAOS_TOL = {CHAOS_TOL} and within the 5-minute window."
                " The recovery-curve reading is degenerate by absence of any"
                " excursion; the per-step series in the archived duckdb is"
                " the supporting record."
            )
        else:
            w(
                f"- Run-level mean_violation is {viol:.4f} (nonzero)."
                " The committed CSV is run-level, so the within-5-minutes"
                " recovery reading **cannot be adjudicated from this file"
                " alone**; LC-H1 is INDETERMINATE at run level and the"
                " per-step series in the archived duckdb is required."
            )
    w("")

    w("## Part B — P99-H1 (live p95 and p99 side by side; live-only numbers)")
    w("")
    w("| cell | family | p95 ms | p99 ms | p99/p95 |")
    w("|---|---|---|---|---|")
    for r in rows:
        for fam in ("crud", "ai"):
            p95 = float(r[f"{fam}_p95_ms"])
            p99 = float(r[f"{fam}_p99_ms"])
            if p95 == 0.0 and p99 == 0.0:
                w(f"| {r['cell']} | {fam} | — | — | (no {fam} traffic in cell) |")
                continue
            w(f"| {r['cell']} | {fam} | {p95:.3f} | {p99:.3f} | {p99 / p95:.3f} |")
    w("")
    all_zero = all(float(r["mean_violation"]) == 0.0 for r in rows)
    if all_zero:
        w(
            "- Violation is zero in every committed row, so the **p99 violation"
            " verdict matches the p95 verdict** in both cells: on the live"
            " cluster the SLO story is unchanged when read at p99 — exactly"
            " the narrow claim P99-H1 permits."
        )
    else:
        w(
            "- Violation verdicts must be compared per percentile before the"
            " P99-H1 sentence may be used; at least one row is nonzero."
        )
    # Computed from the table above (audit 2026-09-26: this sentence was
    # fixed text, "p99/p95 ≈ 2.68 in crud_bursty ... AI nearly flat ≈ 1.00").
    spreads = [(float(r[f"{fam}_p99_ms"]) / float(r[f"{fam}_p95_ms"]), fam, r["cell"])
               for r in rows for fam in ("crud", "ai") if float(r[f"{fam}_p95_ms"]) > 0.0]
    top, top_fam, top_cell = max(spreads)
    ai = [s for s, fam, _ in spreads if fam == "ai"]
    ai_txt = ("no cell carries AI traffic" if not ai
              else f"the AI family under the mock backend is flat at p99/p95 = {ai[0]:.2f}"
              if f"{min(ai):.2f}" == f"{max(ai):.2f}"
              else f"the AI family under the mock backend spans p99/p95 {min(ai):.2f}–{max(ai):.2f}")
    w(
        f"- The largest tail spread is the {top_fam.upper() if top_fam == 'ai' else 'CRUD'} family"
        f" (p99/p95 = {top:.2f} in `{top_cell}`); {ai_txt}. Per ground rule 5 these are"
        " **live-only** readings — no sim table is revisited with them."
    )
    w("")
    w("## Status")
    w("")
    w("- DEFENSE_QA #19 (live-chaos half): closed by Part A — both frozen")
    w("  faults injected live under load, run valid, zero violation through")
    w("  both.")
    w("- DEFENSE_QA #11 (p99 half): closed by Part B — first real live p99")
    w("  numbers recorded, SLO verdict unchanged at p99.")
    w("- Stopping rule honored: one live sitting, no widening; this document")
    w("  is generated once from the committed record.")

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
