"""Paired re-measurement of planning-cell fairness -> PLANNER_CELLS_PAIRED.md.

Audit 2026-09-26 (MEDIUM): `planner_cells.py` and `planner_cells_dealias.py`
draw the monolithic and the partitioned portfolio SEPARATELY from one
generator, so every published ΔJain compares plans for two different tenant
sets -- unpaired noise, and the quoted "-0.0053 worst case" sits inside it.
Here the monolithic plan and both published partition rules (round-robin,
hash) plan the SAME portfolio, over REPS independent portfolios per N, with
the frozen payloads, cell size and N grid imported unchanged. Exploratory:
no hypothesis is re-scored.

    python planner_cells_paired.py --measure   # plans; writes the CSV (minutes)
    python planner_cells_paired.py             # record from the committed CSV
"""

from __future__ import annotations

import argparse
import csv
import re
from pathlib import Path

import numpy as np

import planner_cells as base
import planner_cells_dealias as dealias
import stats

CSV = Path(__file__).resolve().parents[2] / "eval" / "results" / "planner_cells_paired.csv"
RECORD = "PLANNER_CELLS_PAIRED.md"
REPS = 20
RULES = {"round_robin": base.cells_of, "hash": dealias.hash_cells}
BOOT_N = 10_000
BOOT_SEED = 20260926
FIELDS = ["n", "rep", "jain_mono", "jain_round_robin", "jain_hash",
          "viol_mono", "viol_round_robin", "viol_hash"]


def plan_partitioned(tenants: list[dict], rule) -> tuple[float, float, float]:
    plans = {}
    for cell in rule(tenants):
        plans.update(base.PlannerCore().plan(base.cell_payload(cell))["plans"])
    return base.global_metrics(plans)


def measure() -> list[dict]:
    rows = []
    for n in base.TENANT_COUNTS:
        for rep in range(REPS):
            tenants = base.portfolio(n, np.random.default_rng(base.SEED * 1000 + rep))
            mono = base.global_metrics(base.PlannerCore().plan(base.monolithic_payload(tenants))["plans"])
            row = {"n": n, "rep": rep, "jain_mono": mono[0], "viol_mono": mono[1]}
            for name, rule in RULES.items():
                jain, viol, _ = plan_partitioned(tenants, rule)
                row[f"jain_{name}"], row[f"viol_{name}"] = jain, viol
            rows.append(row)
            print(f"n={n:5d} rep={rep:2d} mono {row['jain_mono']:.4f} "
                  f"rr {row['jain_round_robin']:.4f} hash {row['jain_hash']:.4f}", flush=True)
    return rows


def published_unpaired() -> dict[int, tuple[float, float]]:
    """N -> (ΔJain hash, ΔJain round-robin) as PLANNER_CELLS_DEALIAS.md
    published them (each from separately drawn portfolios)."""
    out = {}
    text = (Path(__file__).resolve().parent / "PLANNER_CELLS_DEALIAS.md").read_text(encoding="utf-8")
    for line in text.splitlines():
        m = re.match(r"\|\s*(\d+)\s*\|\s*\d+\s*\|[^|]*\|[^|]*\|\s*([+-][\d.]+)\s*\|\s*([+-][\d.]+)\s*\|", line)
        if m:
            out[int(m.group(1))] = (float(m.group(2)), float(m.group(3)))
    return out


def boot_ci(d: np.ndarray) -> tuple[float, float]:
    rng = np.random.default_rng(BOOT_SEED)
    means = d[rng.integers(0, len(d), size=(BOOT_N, len(d)))].mean(axis=1)
    return float(np.percentile(means, 2.5)), float(np.percentile(means, 97.5))


def load() -> list[dict]:
    with open(CSV, newline="", encoding="utf-8") as f:
        return [{k: (int(v) if k in ("n", "rep") else float(v)) for k, v in r.items()}
                for r in csv.DictReader(f)]


def build(rows: list[dict]) -> str:
    L = ["# Planning-cell fairness, paired: the same portfolio planned three ways", "",
         f"Generated by `planner_cells_paired.py` from `eval/results/planner_cells_paired.csv`. "
         f"For each N, {REPS} independent portfolios (seeds {base.SEED}·1000 + rep); each is planned "
         "monolithically and under both published partition rules, with the frozen payloads, "
         f"cell size ({base.CELL_SIZE}) and N grid of `planner_cells.py`. ΔJain = partitioned − "
         f"monolithic global Jain on the SAME portfolio; 95% bootstrap CI over portfolios "
         f"({BOOT_N:,} resamples, seed {BOOT_SEED}). **Exploratory; no hypothesis is re-scored.**", "",
         "The published records (`PLANNER_CELLS.md`, `PLANNER_CELLS_DEALIAS.md`) drew the monolithic "
         "and partitioned portfolios separately, so their ΔJain compared two different tenant sets "
         "(audit 2026-09-26). The last column is the between-portfolio SD of monolithic Jain: the "
         "noise scale of that unpaired comparison.", "",
         "| N | ΔJain round-robin | 95% CI | published (unpaired) | ΔJain hash | 95% CI | "
         "published (unpaired) | SD of Jain (mono) across portfolios |",
         "|---:|---:|---|---:|---:|---|---:|---:|"]
    published = published_unpaired()
    worst = {}
    for n in base.TENANT_COUNTS:
        sub = [r for r in rows if r["n"] == n]
        mono = np.array([r["jain_mono"] for r in sub])
        cells = [f"{n}"]
        for name in RULES:
            d = np.array([r[f"jain_{name}"] for r in sub]) - mono
            lo, hi = boot_ci(d)
            worst[name] = min(worst.get(name, 0.0), lo)
            pub = published.get(n, (None, None))[1 if name == "round_robin" else 0]
            cells += [f"{d.mean():+.4f}", f"[{lo:+.4f}, {hi:+.4f}]",
                      f"{pub:+.4f}" if pub is not None else "—"]
        cells.append(f"{mono.std(ddof=1):.4f}")
        L.append("| " + " | ".join(cells) + " |")
    L += ["", "## Reading", ""]
    n_worst = min(published, key=lambda n: published[n][0])
    sub = [r for r in rows if r["n"] == n_worst]
    mono = np.array([r["jain_mono"] for r in sub])
    paired_at = float((np.array([r["jain_hash"] for r in sub]) - mono).mean())
    L.append(f"- **The published hash worst case** ({published[n_worst][0]:+.4f} at N = {n_worst}) is "
             f"{abs(published[n_worst][0]) / mono.std(ddof=1):.2f} between-portfolio SDs from zero -- inside "
             f"the noise of an unpaired comparison. Paired, at that N it is {paired_at:+.4f}.")
    for name in RULES:
        within = worst[name] >= -base.DJAIN_TOL
        L.append(f"- **{name.replace('_', '-')}**: the lowest 95% CI bound of paired ΔJain across N is "
                 f"{worst[name]:+.4f}, {'inside' if within else 'OUTSIDE'} the frozen tolerance "
                 f"(−{base.DJAIN_TOL}).")
    L.append("")
    return "\n".join(L) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--measure", action="store_true", help="plan every portfolio and rewrite the CSV")
    args = ap.parse_args()
    if args.measure:
        rows = measure()
        with open(CSV, "w", newline="", encoding="utf-8") as f:
            writer = csv.DictWriter(f, fieldnames=FIELDS)
            writer.writeheader()
            writer.writerows([{k: (f"{r[k]:.10f}" if isinstance(r[k], float) else r[k]) for k in FIELDS}
                              for r in rows])
    out = stats.record_path(RECORD)
    out.write_text(build(load()), encoding="utf-8")
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
