"""Every measurement record in the repository, listed mechanically.

`RESULTS_MASTER.md` calls itself "the single reading entry point for every
measured result". It is a hand-written consolidation, its campaign ledger stops
at session 27, and by session 43 it was missing seven records including the
24 h soak, the S3 floor and the multi-node sitting. A completeness claim that
nothing maintains stops being true quietly.

This file does not replace it. RESULTS_MASTER reconciles and interprets, which
is the author's work; this enumerates, which is a script's. For every record it
reports the hypotheses that record names and whether `scripts/reproduce.py`
regenerates it -- and deliberately NOT the verdicts, because a PASS or a FAIL
misattributed by a regex is worse than no index at all. Verdicts stay in the
records, stated where they were measured.

    python records_index.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import stats  # noqa: E402

HERE = Path(__file__).resolve().parent
REPO_ROOT = stats.REPO_ROOT
RESULTS = REPO_ROOT / "eval" / "results"
RECORD = "RECORDS_INDEX.md"

# A registered hypothesis looks like MN-H1, SK-H4, TL-H3a, BP-H2b.
TAG = re.compile(r"\b([A-Z]{2,4}-H[0-9][a-z]?)\b")
# Documents that are protocol, index or narrative rather than measurement.
NOT_A_RECORD = {"RECORDS_INDEX.md", "RESULTS_MASTER.md", "OSF_REGISTRATION.md",
                "THEORY_V2.md"}


def record_files() -> list[Path]:
    found = [p for p in sorted(HERE.glob("*.md"))
             if not p.name.startswith("PREREG_") and p.name not in NOT_A_RECORD]
    found += sorted(RESULTS.rglob("RESULTS_*.md"))
    return found



def gate_tables() -> tuple[set[str], dict[str, str]]:
    """Read reproduce.py's own tables rather than grepping its source: a record
    named only in the UNGATED table would otherwise count as gated, which is
    the opposite of what that table means."""
    import importlib.util
    spec = importlib.util.spec_from_file_location(
        "_reproduce", REPO_ROOT / "scripts" / "reproduce.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    gated = {r for r, _ in mod.RECORDS} | {r for _, _, r in mod.CAMPAIGN_RECORDS}
    return gated, dict(mod.UNGATED)


def main() -> int:
    gated, ungated = gate_tables()
    rows = []
    for path in record_files():
        text = path.read_text(encoding="utf-8")
        tags = sorted(set(TAG.findall(text)))
        if path.name in gated:
            state = "yes"
        elif path.name in ungated:
            state = "no, reason stated"
        else:
            state = "no"
        rows.append((path.name, tags, state))

    L: list[str] = []
    w = L.append
    w("# Every measurement record, listed mechanically\n")
    w("Generated by `records_index.py`. **An enumeration, not a reading.** "
      "`RESULTS_MASTER.md` consolidates and interprets the contested segments; "
      "this file exists so the *set* of records cannot drift out of date "
      "silently, which is what happened to that document's campaign ledger "
      "between sessions 27 and 43.\n")
    w("\nVerdicts are deliberately absent. A PASS or a FAIL misattributed by a "
      "regular expression would be worse than no index, so each row points at "
      "the record that states its own outcome where it was measured.\n")
    w("")
    w("`reproduced` is whether `scripts/reproduce.py` regenerates the file "
      "and compares it. `no, reason stated` means the record is listed in "
      "that script's `UNGATED` table with the reason it cannot be. A plain "
      "`no` is a record the gate neither covers nor accounts for -- the "
      "RESULTS_* family is held to zero of those by the script itself, and "
      "the remaining rows are older Wave 1-5 documents outside that family.")
    n_gated = sum(1 for _, _, s in rows if s == "yes")
    n_reason = sum(1 for _, _, s in rows if s == "no, reason stated")
    w("")
    w("| | |")
    w("|---|---:|")
    w(f"| records | {len(rows)} |")
    w(f"| regenerated and compared | {n_gated} |")
    w(f"| outside the gate, reason stated | {n_reason} |")
    w(f"| outside the gate, no entry | {len(rows) - n_gated - n_reason} |")
    w("\n| record | hypotheses it names | reproduced |")
    w("|---|---|---|")
    for name, tags, state in rows:
        w(f"| `{name}` | {', '.join(tags) if tags else '-'} | {state} |")
    w("")

    out = stats.record_path(RECORD)
    out.write_bytes(("\n".join(L) + "\n").encode("utf-8"))
    print(f"wrote {out}: {len(rows)} records, {n_gated} regenerated, "
          f"{n_reason} excused, {len(rows) - n_gated - n_reason} neither")
    return 0


if __name__ == "__main__":
    sys.exit(main())
