apiVersion: v1
kind: Secret
metadata:
  name: {{ include "polyforge.name" . }}
  labels:
    {{- include "polyforge.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-key: {{ .Values.adminKey | quote }}
